---
title: "CENT S1-S2 Clustering Diagnostics"
output:
  html_notebook: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r}
library(readr)
library(dplyr)
```

```{r}
# read in kmeans diagnostics files
diagnostics_kmeans_C3_raw <- read.csv("diagnostics_kmeans_C3_raw.csv") %>% select(-X)
diagnostics_kmeans_C3_growth <- read.csv("diagnostics_kmeans_C3_growth.csv") %>% select(-X)
diagnostics_kmeans_LS_raw <- read.csv("diagnostics_kmeans_LS_raw.csv") %>% select(-X)
diagnostics_kmeans_LS_growth <- read.csv("diagnostics_kmeans_LS_growth.csv") %>% select(-X)
diagnostics_kmeans_C3_LS_raw <- read.csv("diagnostics_kmeans_C3_LS_raw.csv") %>% select(-X)
diagnostics_kmeans_C3_LS_growth <- read.csv("diagnostics_kmeans_C3_LS_growth.csv") %>% select(-X)
diagnostics_kmeans_raw_growth <- read.csv("diagnostics_kmeans_raw_growth.csv") %>% select(-X)
```

```{r}
# combine all kmeans diagnostics
diagnostics_kmeans <- rbind(diagnostics_kmeans_C3_raw, diagnostics_kmeans_C3_growth, 
                            diagnostics_kmeans_LS_raw, diagnostics_kmeans_LS_growth, 
                            diagnostics_kmeans_C3_LS_raw, diagnostics_kmeans_C3_LS_growth, 
                            diagnostics_kmeans_raw_growth)
```

```{r}
# read in kshape/dtw diagnostics files
diagnostics_kshape_dtw_C3_raw <- read.csv("diagnostics_kshape_dtw_C3_raw.csv") %>% select(-X)
diagnostics_kshape_dtw_C3_growth <- read.csv("diagnostics_kshape_dtw_C3_growth.csv") %>% select(-X)
diagnostics_kshape_dtw_LS_raw <- read.csv("diagnostics_kshape_dtw_LS_raw.csv") %>% select(-X)
diagnostics_kshape_dtw_LS_growth <- read.csv("diagnostics_kshape_dtw_LS_growth.csv") %>% select(-X)
diagnostics_kshape_dtw_C3_LS_raw <- read.csv("diagnostics_kshape_dtw_C3_LS_raw.csv") %>% select(-X)
diagnostics_kshape_dtw_C3_LS_growth <- read.csv("diagnostics_kshape_dtw_C3_LS_growth.csv") %>% select(-X)
diagnostics_kmeans_raw_growth <- read.csv("diagnostics_kmeans_raw_growth.csv") %>% select(-X)
```

```{r}
# combine all kshape/dtw diagnostics
diagnostics_kshape_dtw <- rbind(diagnostics_kshape_dtw_C3_raw, diagnostics_kshape_dtw_C3_growth, 
                                diagnostics_kshape_dtw_LS_raw, diagnostics_kshape_dtw_LS_growth, 
                                diagnostics_kshape_dtw_C3_LS_raw, diagnostics_kshape_dtw_C3_LS_growth, 
                                diagnostics_kmeans_raw_growth)
```

```{r}
# read in pca diagnostics files
diagnostics_pca_C3_raw <- read.csv("diagnostics_pca_C3_raw.csv") %>% select(-X)
diagnostics_pca_C3_growth <- read.csv("diagnostics_pca_C3_growth.csv") %>% select(-X)
diagnostics_pca_LS_raw <- read.csv("diagnostics_pca_LS_raw.csv") %>% select(-X)
diagnostics_pca_LS_growth <- read.csv("diagnostics_pca_LS_growth.csv") %>% select(-X)
diagnostics_pca_C3_LS_raw <- read.csv("diagnostics_pca_C3_LS_raw.csv") %>% select(-X)
diagnostics_pca_C3_LS_growth <- read.csv("diagnostics_pca_C3_LS_growth.csv") %>% select(-X)
diagnostics_pca_raw_growth <- read.csv("diagnostics_pca_raw_growth.csv") %>% select(-X)
```

```{r}
# combine all pca diagnostics
diagnostics_pca <- rbind(diagnostics_pca_C3_raw, diagnostics_pca_C3_growth, 
                         diagnostics_pca_LS_raw, diagnostics_pca_LS_growth, 
                         diagnostics_pca_C3_LS_raw, diagnostics_pca_C3_LS_growth, 
                         diagnostics_pca_raw_growth)
```

```{r}
# read in tadpole diagnostics files
diagnostics_tadpole_C3_raw <- read.csv("diagnostics_tadpole_C3_raw.csv") %>% select(-X)
diagnostics_tadpole_C3_growth <- read.csv("diagnostics_tadpole_C3_growth.csv") %>% select(-X)
diagnostics_tadpole_LS_raw <- read.csv("diagnostics_tadpole_LS_raw.csv") %>% select(-X)
diagnostics_tadpole_LS_growth <- read.csv("diagnostics_tadpole_LS_growth.csv") %>% select(-X)
diagnostics_tadpole_C3_LS_raw <- read.csv("diagnostics_tadpole_C3_LS_raw.csv") %>% select(-X)
diagnostics_tadpole_C3_LS_growth <- read.csv("diagnostics_tadpole_C3_LS_growth.csv") %>% select(-X)
diagnostics_tadpole_raw_growth <- read.csv("diagnostics_tadpole_raw_growth.csv") %>% select(-X)
```

```{r}
# combine all tadpole diagnostics
diagnostics_tadpole <- rbind(diagnostics_tadpole_C3_raw, diagnostics_tadpole_C3_growth, 
                             diagnostics_tadpole_LS_raw, diagnostics_tadpole_LS_growth, 
                             diagnostics_tadpole_C3_LS_raw, diagnostics_tadpole_C3_LS_growth, 
                             diagnostics_tadpole_raw_growth)
```

```{r}
# combine all diagnostics
diagnostics <- rbind(diagnostics_kmeans, diagnostics_kshape_dtw, 
                     diagnostics_pca, diagnostics_tadpole)
```

```{r}
# write new file with all diagnostics
write.csv(diagnostics, "diagnostics.csv")
```

```{r}
# determine best clusters
best_clusters <- diagnostics %>% group_by(stream, data, season) %>% 
  summarise(largest_between = paste(cluster.number[which.max(average.between)], 
                                    algorithm[which.max(average.between)], sep = " "), 
            smallest_within = paste(cluster.number[which.min(average.within)], 
                                    algorithm[which.min(average.within)], sep = " "), 
            smallest_wb_ratio = paste(cluster.number[which.min(wb.ratio)], 
                                      algorithm[which.min(wb.ratio)], sep = " "), 
            smallest_gap = paste(cluster.number[which.min(widestgap)], 
                                 algorithm[which.min(widestgap)], sep = " "), 
            largest_dunn2 = paste(cluster.number[which.max(dunn2)], 
                                  algorithm[which.max(dunn2)], sep = " "), 
            largest_sil = paste(cluster.number[which.max(avg.silwidth)], 
                                algorithm[which.max(avg.silwidth)], sep = " "), 
            smallest_ss = paste(cluster.number[which.min(within.cluster.ss)], 
                                algorithm[which.min(within.cluster.ss)], sep = " "))

best_clusters$best <- apply(best_clusters, 1, function(x) names(which(table(x) == max(table(x)))))
```

```{r}
# write file with best clusters
best_clusters <- apply(best_clusters, 2, as.character)
write.csv(best_clusters, "best_clusters.csv")
```

