---
title: "CENT S1-S2 K-Shape and DTW Clustering on LS Growth"
output:
  html_notebook: default
  html_document: default
---

```{r}
##################################################################################
# inputs: dct_LS_growth.csv, dct_spread_LS_growth.csv, 
#         dct_LS_growth_s1_s2.csv, dct_LS_growth_cont.csv,  
#         dct_spread_LS_growth_cont.csv
#
# purpose: K-Shape and Dynamic Time Warp clustering (clusters for S1, S2,
#          and S1 & S2 normalized separately and together)
##################################################################################
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r}
library(dplyr)
library(broom)
library(ggplot2)
library(plotly)
library(dtwclust)
library(fpc)
```

# Season 1 Time Series Clustering

From example here: https://cran.r-project.org/web/packages/dtwclust/vignettes/dtwclust.pdf.

```{r}
#read in long and wide format data
dct_df <- read.csv("dct_LS_growth.csv")
dct_spread <- read.csv("dct_spread_LS_growth.csv")
```

```{r}
#filter wide data to only cluster on season 1
cluster_s1 <- dct_spread %>% 
  filter(Season_num == 1) %>%
  ungroup() %>%
  select(-X, -Network, -Season_num, -Show_Name)
```

## K-Shape Clustering 

```{r}
#partitional clustering with 2 through 5 clusters
#using shape-based distance for the curves
#clustering around shape centroid
kshape_s1 <- tsclust(cluster_s1, 
                     type = 'partitional',
                     k = 2:5,
                     preproc = zscore,
                     distance = 'sbd',
                     centroid = 'shape',
                     trace = FALSE,
                     seed = 12)

names(kshape_s1) <- paste0('k_', 2:5)

#apply internal clustering validity indices
#including silhouette, Dunn, and others (see ?cvi documentation in R)
sapply(kshape_s1, cvi, type = 'internal')

#give best cluster number based on silhouette width
#a measure of how similar the object is to its own cluster compared to others
which.max(sapply(kshape_s1, cvi, type = 'internal')['Sil',])
```

```{r}
#export cluster predictions to the main data set and visualize in ggplot
clusters_s1_shape5_spread <- dct_spread %>% filter(Season_num == 1)
clusters_s1_shape5_spread$cluster_shape_5 <- kshape_s1$k_5@cluster

clusters_s1_shape5 <- merge(clusters_s1_shape5_spread[, c("cluster_shape_5", 
                                       "Show_Name")], 
                            dct_df, by = "Show_Name")
```

```{r}
clusters_s1_shape5_plot <- clusters_s1_shape5 %>%
  filter(Season_num == 1) %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster_shape_5, nrow = 3) +  
  theme(axis.title.x = element_blank(), 
        axis.title.y = element_blank())

ggplotly(clusters_s1_shape5_plot) %>% 
  layout(title = "Season 1 with 5 K-Shape Clusters (LS Growth)", 
         margin = list(t = 150))
```

```{r}
#list shows in each cluster
s1_5clusters_kshape <- list(as.character(unique(clusters_s1_shape5[clusters_s1_shape5$cluster_shape_5 == 1,]$Show_Name)), 
                            as.character(unique(clusters_s1_shape5[clusters_s1_shape5$cluster_shape_5 == 2,]$Show_Name)),
                            as.character(unique(clusters_s1_shape5[clusters_s1_shape5$cluster_shape_5 == 3,]$Show_Name)),
                            as.character(unique(clusters_s1_shape5[clusters_s1_shape5$cluster_shape_5 == 4,]$Show_Name)),
                            as.character(unique(clusters_s1_shape5[clusters_s1_shape5$cluster_shape_5 == 5,]$Show_Name)))
s1_5clusters_kshape
```

```{r}
# PLOT FOR S1 CLUSTERS & S2 TRENDS

#create subset of show curves from season 2
s2_spread <- dct_spread %>% 
  filter(Season_num == 2) %>%
  ungroup() %>%
  select(-X, -Network, -Season_num)

#change column names range to append to season 1 curves with cluster variable
s2_spread_newcols <- c(paste("X", 101:200, sep = ""))
colnames(s2_spread)[2:ncol(s2_spread)] <- c(s2_spread_newcols)

s1_5clusters_kshape_s2_trends <- bind_cols(clusters_s1_shape5_spread, 
                                           s2_spread[, 2:ncol(s2_spread)])

s1_5clusters_kshape_s2_trends <- merge(s1_5clusters_kshape_s2_trends[, c("cluster_shape_5", 
                                                                         "Show_Name")], 
                                       dct_df, by = "Show_Name")

#re-number rows to make continuous over 200 periods for both seasons
dct_s1_5clusters_kshape_s2_trends <- s1_5clusters_kshape_s2_trends %>% 
  filter(Season_num == 1 | Season_num == 2) %>% 
  group_by(Network, Show_Name) %>% 
  mutate(period = row_number())

s1_5clusters_kshape_s2_trends_plot <- dct_s1_5clusters_kshape_s2_trends %>%
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster_shape_5, nrow = 3) + 
  theme(axis.title.x = element_blank(), 
        axis.title.y = element_blank())

ggplotly(s1_5clusters_kshape_s2_trends_plot) %>% 
  layout(title = "Season 1 with 5 K-Shape Clusters & Season 2 Trends (LS Growth)", 
         margin = list(t = 150))
```

## Dynamic Time Warp Clustering

```{r}
#partitional clustering with 2 through 5 clusters
#using dynamic time warping distance for the curves
#with partitioning around mediods
#see dtwclust documentation in R for further information
dtw_s1 <- tsclust(cluster_s1,
                  type = 'partitional',
                  k = 2:5,
                  distance = 'dtw_lb',
                  centroid = 'pam',
                  control = partitional_control(iter.max = 25),
                  args = tsclust_args(dist = list()),
                  window.size = 20,
                  trace = FALSE,
                  seed = 12)

names(dtw_s1) <- paste0('k_', 2:5)

#apply internal clustering validity indices
sapply(dtw_s1, cvi)

#give best cluster number based on silhouette width
#a measure of how similar the object is to its own cluster compared to others
which.max(sapply(dtw_s1, cvi, type = 'internal')['Sil',])
```

```{r}
#export cluster predictions to the main data set and visualize in ggplot
clusters_s1_dtw3_spread <- dct_spread %>% filter(Season_num == 1)
clusters_s1_dtw3_spread$cluster_dtw_3 <- dtw_s1$k_3@cluster

clusters_s1_dtw3 <- merge(clusters_s1_dtw3_spread[, c("cluster_dtw_3", "Show_Name")], 
                          dct_df, by = "Show_Name")
```

```{r}
clusters_s1_dtw3_plot <- clusters_s1_dtw3 %>%
  filter(Season_num == 1) %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster_dtw_3, nrow = 3) +  
  theme(axis.title.x = element_blank(), 
        axis.title.y = element_blank())

ggplotly(clusters_s1_dtw3_plot) %>% 
  layout(title = "Season 1 with 3 DTW Clusters (LS Growth)", 
         margin = list(t = 150))
```

```{r}
s1_3clusters_dtw <- list(as.character(unique(clusters_s1_dtw3[clusters_s1_dtw3$cluster_dtw_3 == 1,]$Show_Name)), 
                         as.character(unique(clusters_s1_dtw3[clusters_s1_dtw3$cluster_dtw_3 == 2,]$Show_Name)), 
                         as.character(unique(clusters_s1_dtw3[clusters_s1_dtw3$cluster_dtw_3 == 3,]$Show_Name)))
s1_3clusters_dtw
```

```{r}
# PLOT FOR S1 CLUSTERS & S2 TRENDS
s1_3clusters_dtw_s2_trends <- bind_cols(clusters_s1_dtw3_spread, 
                                        s2_spread[, 2:ncol(s2_spread)])

s1_3clusters_dtw_s2_trends <- merge(s1_3clusters_dtw_s2_trends[, c("cluster_dtw_3", 
                                                                   "Show_Name")], 
                                    dct_df, by = "Show_Name")

dct_s1_3clusters_dtw_s2_trends <- s1_3clusters_dtw_s2_trends %>% 
  filter(Season_num == 1 | Season_num == 2) %>% 
  group_by(Network, Show_Name) %>% 
  mutate(period = row_number())

s1_3clusters_dtw_s2_trends_plot <- dct_s1_3clusters_dtw_s2_trends %>%
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster_dtw_3, nrow = 3) + 
  theme(axis.title.x = element_blank(), 
        axis.title.y = element_blank())

ggplotly(s1_3clusters_dtw_s2_trends_plot) %>% 
  layout(title = "Season 1 with 3 DTW Clusters & Season 2 Trends (LS Growth)", 
         margin = list(t = 150))
```


-----------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------


# Season 2 Time Series Clustering

```{r}
#same code as for season 1
cluster_s2 <- dct_spread %>% 
  filter(Season_num == 2) %>%
  ungroup() %>%
  select(-X, -Network, -Season_num, -Show_Name)
```

## K-Shape Clustering 

```{r}
kshape_s2 <- tsclust(cluster_s2, 
                     type = 'partitional',
                     k = 2:5,
                     preproc = zscore,
                     distance = 'sbd',
                     centroid = 'shape',
                     trace = FALSE,
                     seed = 12)

names(kshape_s2) <- paste0('k_', 2:5)
sapply(kshape_s2, cvi, type = 'internal')
which.max(sapply(kshape_s2, cvi, type = 'internal')['Sil',])
```

```{r}
clusters_s2_shape2_spread <- dct_spread %>% filter(Season_num == 2)
clusters_s2_shape2_spread$cluster_shape_2 <- kshape_s2$k_2@cluster

clusters_s2_shape2 <- merge(clusters_s2_shape2_spread[, c("cluster_shape_2", "Show_Name")], 
                            dct_df, by = "Show_Name")
```

```{r}
clusters_s2_shape2_plot <- clusters_s2_shape2 %>%
  filter(Season_num == 2) %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster_shape_2, nrow = 2) +  
  theme(axis.title.x = element_blank(), 
        axis.title.y = element_blank())

ggplotly(clusters_s2_shape2_plot) %>% 
  layout(title = "Season 2 with 2 K-Shape Clusters (LS Growth)", 
         margin = list(t = 150))
```

```{r}
s2_2clusters_kshape <- list(as.character(unique(clusters_s2_shape2[clusters_s2_shape2$cluster_shape_2 == 1,]$Show_Name)), 
                            as.character(unique(clusters_s2_shape2[clusters_s2_shape2$cluster_shape_2 == 2,]$Show_Name)))
s2_2clusters_kshape
```

## Dynamic Time Warp Clustering

```{r}
dtw_s2 <- tsclust(cluster_s2,
                  type = 'partitional',
                  k = 2:5,
                  distance = 'dtw_lb',
                  centroid = 'pam',
                  control = partitional_control(iter.max = 25),
                  args = tsclust_args(dist = list()),
                  window.size = 20,
                  trace = FALSE,
                  seed = 12)

names(dtw_s2) <- paste0('k_', 2:5)
sapply(dtw_s2, cvi)
which.max(sapply(dtw_s2, cvi, type = 'internal')['Sil',])
```

```{r}
clusters_s2_dtw2_spread <- dct_spread %>% filter(Season_num == 2)
clusters_s2_dtw2_spread$cluster_dtw_2 <- dtw_s2$k_2@cluster

clusters_s2_dtw2 <- merge(clusters_s2_dtw2_spread[, c("cluster_dtw_2", "Show_Name")], 
                          dct_df, by = "Show_Name")
```

```{r}
clusters_s2_dtw2_plot <- clusters_s2_dtw2 %>%
  filter(Season_num == 2) %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster_dtw_2) +  
  theme(axis.title.x = element_blank(), 
        axis.title.y = element_blank())

ggplotly(clusters_s2_dtw2_plot) %>% 
  layout(title = "Season 2 with 2 DTW Clusters (LS Growth)", 
         margin = list(t = 150))
```

```{r}
s2_2clusters_dtw <- list(as.character(unique(clusters_s2_dtw2[clusters_s2_dtw2$cluster_dtw_2 == 1,]$Show_Name)), 
                         as.character(unique(clusters_s2_dtw2[clusters_s2_dtw2$cluster_dtw_2 == 2,]$Show_Name)))
s2_2clusters_dtw
```


-----------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------


# S1-S2 Continuous Time Series Clustering

```{r}
#code is the same as clustering on one season
#but using season 1 to season 2 normalized together
dct_cont <- read.csv("dct_LS_growth_cont.csv")
dct_spread_cont <- read.csv("dct_spread_LS_growth_cont.csv")
cluster_cont <- dct_spread_cont %>%
  select(-X, -Network, -Show_Name)
```

## K-Shape Clustering 

```{r}
kshape_cont <- tsclust(cluster_cont, 
                       type = 'partitional',
                       k = 2:5,
                       preproc = zscore,
                       distance = 'sbd',
                       centroid = 'shape',
                       trace = FALSE,
                       seed = 12)

names(kshape_cont) <- paste0('k_', 2:5)
sapply(kshape_cont, cvi, type = 'internal')
which.max(sapply(kshape_cont, cvi, type = 'internal')['Sil',])
```

```{r}
clusters_cont_shape5_spread <- dct_spread_cont
clusters_cont_shape5_spread$cluster_shape_5 <- kshape_cont$k_5@cluster

clusters_cont_shape5 <- merge(clusters_cont_shape5_spread[, c("cluster_shape_5", "Show_Name")], 
                              dct_cont, by = "Show_Name")
```

```{r}
clusters_cont_shape5_plot <- clusters_cont_shape5 %>%
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster_shape_5, nrow = 3) +  
  theme(axis.title.x = element_blank(), 
        axis.title.y = element_blank())

ggplotly(clusters_cont_shape5_plot) %>% 
  layout(title = "S1-S2 (Continuous) with 5 K-Shape Clusters (LS Growth)", 
         margin = list(t = 150))
```

```{r}
cont_5clusters_kshape <- list(as.character(unique(clusters_cont_shape5[clusters_cont_shape5$cluster_shape_5 == 1,]$Show_Name)), 
                              as.character(unique(clusters_cont_shape5[clusters_cont_shape5$cluster_shape_5 == 2,]$Show_Name)), 
                              as.character(unique(clusters_cont_shape5[clusters_cont_shape5$cluster_shape_5 == 3,]$Show_Name)), 
                              as.character(unique(clusters_cont_shape5[clusters_cont_shape5$cluster_shape_5 == 4,]$Show_Name)), 
                              as.character(unique(clusters_cont_shape5[clusters_cont_shape5$cluster_shape_5 == 5,]$Show_Name)))
cont_5clusters_kshape
```

## Dynamic Time Warp Clustering

```{r}
dtw_cont <- tsclust(cluster_cont,
                    type = 'partitional',
                    k = 2:5,
                    distance = 'dtw_lb',
                    centroid = 'pam',
                    control = partitional_control(iter.max = 25),
                    args = tsclust_args(dist = list()),
                    window.size = 20,
                    trace = FALSE,
                    seed = 12)

names(dtw_cont) <- paste0('k_', 2:5)
sapply(dtw_cont, cvi)
which.max(sapply(dtw_cont, cvi, type = 'internal')['Sil',])
```

```{r}
clusters_cont_dtw4_spread <- dct_spread_cont
clusters_cont_dtw4_spread$cluster_dtw_4 <- dtw_cont$k_4@cluster

clusters_cont_dtw4 <- merge(clusters_cont_dtw4_spread[, c("cluster_dtw_4", "Show_Name")], 
                            dct_cont, by = "Show_Name")
```

```{r}
clusters_cont_dtw4_plot <- clusters_cont_dtw4 %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster_dtw_4) +  
  theme(axis.title.x = element_blank(), 
        axis.title.y = element_blank())

ggplotly(clusters_cont_dtw4_plot) %>% 
  layout(title = "S1-S2 (Continuous) with 4 DTW Clusters (LS Growth)", 
         margin = list(t = 150))
```

```{r}
cont_4clusters_dtw <- list(as.character(unique(clusters_cont_dtw4[clusters_cont_dtw4$cluster_dtw_4 == 1,]$Show_Name)), 
                           as.character(unique(clusters_cont_dtw4[clusters_cont_dtw4$cluster_dtw_4 == 2,]$Show_Name)), 
                           as.character(unique(clusters_cont_dtw4[clusters_cont_dtw4$cluster_dtw_4 == 3,]$Show_Name)), 
                           as.character(unique(clusters_cont_dtw4[clusters_cont_dtw4$cluster_dtw_4 == 4,]$Show_Name)))
cont_4clusters_dtw
```


-----------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------


# S1-S2 Non-Continuous Time Series Clustering

```{r}
#create data frame for season 1 and season 2 appended over 200 periods
temp1 <- filter(dct_spread, Season_num == 1)
temp2 <- filter(dct_spread, Season_num == 2)
temp2_newcols <- c(paste("X", 101:200, sep = ""))
colnames(temp2)[5:ncol(temp2)] <- c(temp2_newcols)

dct_spread_s1_s2 <- bind_cols(temp1, temp2[, 5:ncol(temp2)])
rm(temp1, temp2, temp2_newcols)

cluster_s1_s2 <- dct_spread_s1_s2 %>%
  select(-X, -Network, -Season_num, -Show_Name)

dct_s1_s2 <- read.csv("dct_LS_growth_s1_s2.csv")
```

```{r}
kshape_s1_s2 <- tsclust(cluster_s1_s2, 
                        type = 'partitional',
                        k = 2:5,
                        preproc = zscore,
                        distance = 'sbd',
                        centroid = 'shape',
                        trace = FALSE,
                        seed = 12)

names(kshape_s1_s2) <- paste0('k_', 2:5)
sapply(kshape_s1_s2, cvi, type = 'internal')
which.max(sapply(kshape_s1_s2, cvi, type = 'internal')['Sil',])
```

```{r}
clusters_s1_s2_shape5_spread <- dct_spread_s1_s2
clusters_s1_s2_shape5_spread$cluster_shape_5 <- kshape_s1_s2$k_5@cluster

clusters_s1_s2_shape5 <- merge(clusters_s1_s2_shape5_spread[, c("cluster_shape_5", "Show_Name")], 
                               dct_s1_s2, by = "Show_Name")
```

```{r}
clusters_s1_s2_shape5_plot <- clusters_s1_s2_shape5 %>%
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster_shape_5, nrow = 3) +  
  theme(axis.title.x = element_blank(), 
        axis.title.y = element_blank())

ggplotly(clusters_s1_s2_shape5_plot) %>% 
  layout(title = "S1-S2 (Non-Continuous) with 5 K-Shape Clusters (LS Growth)", 
         margin = list(t = 150))
```

```{r}
s1_s2_5clusters_kshape <- list(as.character(unique(clusters_s1_s2_shape5[clusters_s1_s2_shape5$cluster_shape_5 == 1,]$Show_Name)), 
                               as.character(unique(clusters_s1_s2_shape5[clusters_s1_s2_shape5$cluster_shape_5 == 2,]$Show_Name)), 
                               as.character(unique(clusters_s1_s2_shape5[clusters_s1_s2_shape5$cluster_shape_5 == 3,]$Show_Name)), 
                               as.character(unique(clusters_s1_s2_shape5[clusters_s1_s2_shape5$cluster_shape_5 == 4,]$Show_Name)), 
                               as.character(unique(clusters_s1_s2_shape5[clusters_s1_s2_shape5$cluster_shape_5 == 5,]$Show_Name)))
s1_s2_5clusters_kshape
```

## Dynamic Time Warp Clustering

```{r}
dtw_s1_s2 <- tsclust(cluster_s1_s2,
                     type = 'partitional',
                     k = 2:5,
                     distance = 'dtw_lb',
                     centroid = 'pam',
                     control = partitional_control(iter.max = 25),
                     args = tsclust_args(dist = list()),
                     window.size = 20,
                     trace = FALSE,
                     seed = 12)

names(dtw_s1_s2) <- paste0('k_', 2:5)
sapply(dtw_s1_s2, cvi)
which.max(sapply(dtw_s1_s2, cvi, type = 'internal')['Sil',])
```

```{r}
clusters_s1_s2_dtw3_spread <- dct_spread_s1_s2
clusters_s1_s2_dtw3_spread$cluster_dtw_3 <- dtw_s1_s2$k_3@cluster

clusters_s1_s2_dtw3 <- merge(clusters_s1_s2_dtw3_spread[, c("cluster_dtw_3", "Show_Name")], 
                             dct_s1_s2, by = "Show_Name")
```

```{r}
clusters_s1_s2_dtw3_plot <- clusters_s1_s2_dtw3 %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster_dtw_3, nrow = 3) +  
  theme(axis.title.x = element_blank(), 
        axis.title.y = element_blank())

ggplotly(clusters_s1_s2_dtw3_plot) %>% 
  layout(title = "S1-S2 (Non-Continuous) with 3 DTW Clusters (LS Growth)", 
         margin = list(t = 150))
```

```{r}
s1_s2_3clusters_dtw <- list(as.character(unique(clusters_s1_s2_dtw3[clusters_s1_s2_dtw3$cluster_dtw_3 == 1,]$Show_Name)), 
                            as.character(unique(clusters_s1_s2_dtw3[clusters_s1_s2_dtw3$cluster_dtw_3 == 2,]$Show_Name)), 
                            as.character(unique(clusters_s1_s2_dtw3[clusters_s1_s2_dtw3$cluster_dtw_3 == 3,]$Show_Name)))
s1_s2_3clusters_dtw
```

# Diagnostics

```{r}
# create distance matrices for clusters
s1_5clusters_d <- dist(clusters_s1_shape5_spread[, 5:105])
s2_2clusters_d <- dist(clusters_s2_shape2_spread[, 5:105])
cont_5clusters_d <- dist(clusters_cont_shape5_spread[, 4:104])
s1_s2_5clusters_d <- dist(clusters_s1_s2_shape5_spread[, 5:204])
s1_3clusters_d <- dist(clusters_s1_dtw3_spread[, 5:105])
s2_2clusters_d <- dist(clusters_s2_dtw2_spread[, 5:105])
cont_4clustdtw_d <- dist(clusters_cont_dtw4_spread[, 4:104])
s1_s2_3clusters_d <- dist(clusters_s1_s2_dtw3_spread[, 5:204])

# diagnostics
diagnostics_kshape_LS_growth_s1_5cl <- cluster.stats(s1_5clusters_d, as.numeric(clusters_s1_shape5_spread$cluster_shape_5))
diagnostics_kshape_LS_growth_s2_2cl <- cluster.stats(s2_2clusters_d, as.numeric(clusters_s2_shape2_spread$cluster_shape_2))
diagnostics_kshape_LS_growth_cont_5cl <- cluster.stats(cont_5clusters_d, as.numeric(clusters_cont_shape5_spread$cluster_shape_5))
diagnostics_kshape_LS_growth_sep_5cl <- cluster.stats(s1_s2_5clusters_d, as.numeric(clusters_s1_s2_shape5_spread$cluster_shape_5))
diagnostics_dtw_LS_growth_s1_3cl <- cluster.stats(s1_3clusters_d, as.numeric(clusters_s1_dtw3_spread$cluster_dtw_3))
diagnostics_dtw_LS_growth_s2_2cl <- cluster.stats(s2_2clusters_d, as.numeric(clusters_s2_dtw2_spread$cluster_dtw_2))
diagnostics_dtw_LS_growth_cont_4cl <- cluster.stats(cont_4clustdtw_d, as.numeric(clusters_cont_dtw4_spread$cluster_dtw_4))
diagnostics_dtw_LS_growth_sep_3cl <- cluster.stats(s1_s2_3clusters_d, as.numeric(clusters_s1_s2_dtw3_spread$cluster_dtw_3))

# gather diagnostic names and list all diagnostics objects
d_names <- ls()[grep("diagnostics", ls())]
d_list <- mget(ls()[grep("diagnostics", ls())])

# generate df with statsitics of interest for comparison
diagnostic_df <- as.data.frame(NA)

for (n in 1:length(d_names)){
  diagnostic_df[n, 1] <- paste(d_names[n])
  diagnostic_df[n, 2] <- d_list[[n]]["average.between"]
  diagnostic_df[n, 3] <- d_list[[n]]["average.within"]
  diagnostic_df[n, 4] <- d_list[[n]]["wb.ratio"]
  diagnostic_df[n, 5] <- d_list[[n]]["widestgap"]
  diagnostic_df[n, 6] <- d_list[[n]]["dunn2"]
  diagnostic_df[n, 7] <- d_list[[n]]["avg.silwidth"]
  diagnostic_df[n, 8] <- d_list[[n]]["within.cluster.ss"]
  diagnostic_df[n, 9] <- d_list[[n]]["cluster.number"]
}

# add information for decision making
colnames(diagnostic_df)[1] <- "name"

diagnostic_df$name <- sub("diagnostics_", "", diagnostic_df$name)

diagnostic_df$algorithm <- ifelse(grepl("kmeans", diagnostic_df$name) == 1, "kmeans",
                                  ifelse(grepl("kshape", diagnostic_df$name) == 1, "kshape",
                                         ifelse(grepl("PCA", diagnostic_df$name) == 1, "PCA",
                                                ifelse(grepl("pca", diagnostic_df$name) == 1, "PCA",
                                                       ifelse(grepl("tadpole", diagnostic_df$name) == 1, "tadpole",
                                                              ifelse(grepl("dtw", diagnostic_df$name) == 1, "DTW", 0))))))

diagnostic_df$season <- ifelse(grepl("s1", diagnostic_df$name) == 1, "s1",
                               ifelse(grepl("s2", diagnostic_df$name) == 1, "s2",
                                      ifelse(grepl("sep", diagnostic_df$name) == 1, "sep",
                                             ifelse(grepl("cont", diagnostic_df$name) == 1, "cont", 0))))

diagnostic_df$stream <- ifelse(grepl("C3", diagnostic_df$name) == 1, "C3",
                               ifelse(grepl("LS", diagnostic_df$name) == 1, "LS", 0))

diagnostic_df$data <- ifelse(grepl("raw", diagnostic_df$name) == 1, "raw",
                             ifelse(grepl("growth", diagnostic_df$name) == 1, "growth",
                                    ifelse(grepl("rebase", diagnostic_df$name) == 1, "rebase",0)))
```

```{r}
# write table
write.csv(diagnostic_df, "diagnostics_kshape_dtw_LS_growth.csv")
```
