---
title: "CENT C3 vs LS"
output: 
  flexdashboard::flex_dashboard:
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
options(scipen = 999, digits = 3)
```

```{r}
library(dplyr)
library(ggplot2)
library(scales)
library(plotly)
```

```{r}
data <- read.csv("s1_s2_data.csv") %>% select(-X)
stats_by_season <- read.csv("s1_s2_stats_by_season.csv") %>% select(-X)

clusters_C3_raw <- read.csv("kmeans_C3_raw_s1_5cl_s2trends.csv") %>% select(-X)
clusters_LS_raw <- read.csv("kmeans_LS_raw_s1_5cl_s2trends.csv") %>% select(-X)
```

```{r}
my_theme <- theme(panel.background = element_blank(), 
                  panel.grid.major = element_line(color = "#d8d8d8", linetype = "dotted"), 
                  panel.grid.major.x = element_blank(), 
                  plot.title = element_text(hjust = 0.5),
                  legend.position = "bottom",
                  axis.line.y = element_blank(),
                  axis.ticks.y = element_blank(),
                  axis.title.x = element_blank(),
                  axis.text.x = element_blank(),
                  axis.ticks.x = element_blank(),
                  axis.line.x = element_line(color = "#d8d8d8", linetype = "dashed"),
                  strip.background = element_blank())
```

C3 vs LS Averages
===================================================================================================

Sidebar {.sidebar data-width=150}
---------------------------------------------------------------------------------------------------

```{r}
selectInput("network", label = "Network:",
            choices = unique(data$Network))

selectInput("genre", label = "Genre:",
            choices = unique(data$Genre))

selectInput("dow", label = "Day of Week:",
            choices = unique(data$DOW))

selectInput("start", label = "Start Time:",
            choices = unique(data$Start_Time))

selectInput("duration", label = "Program Duration:",
            choices = unique(data$Program_Duration))

selectInput("qtr", label = "Cable Quarter:",
            choices = unique(data$Cable_Qtr))

selectInput("year", label = "Broadcast Year:",
            choices = unique(data$Broadcast_Year))
```

Column {.tabset data-width=450}
---------------------------------------------------------------------------------------------------

### Network

```{r}
data %>% filter(Season_num == 1) %>% 
  group_by(Network) %>% 
  summarise(avg_LS = mean(LS_Impressions), 
            avg_C3 = mean(C3_Impressions)) %>% 
  plot_ly(x = ~Network, colors = c("#31a354", "#3182bd")) %>%
  add_trace(y = ~avg_C3, color = "C3 Impressions", type = "bar") %>%
  add_trace(y = ~avg_LS, color = "LS Impressions", type = "bar") %>% 
  layout(title = "Average C3 vs LS Impressions by Network", 
         yaxis = list(title = ""))
```

### Genre

```{r}
data %>% filter(Season_num == 1) %>%  
  group_by(Genre) %>% 
  summarise(avg_LS = mean(LS_Impressions), 
            avg_C3 = mean(C3_Impressions)) %>% 
  plot_ly(x = ~Genre, colors = c("#31a354", "#3182bd")) %>%
  add_trace(y = ~avg_C3, color = "C3", type = "bar") %>%
  add_trace(y = ~avg_LS, color = "LS", type = "bar") %>% 
  layout(title = "Average C3 vs LS Impressions by Genre", 
         xaxis = list(title = "Genre"),
         yaxis = list(title = ""))
```

### DOW

```{r}
data %>% filter(Season_num == 1) %>% 
  group_by(DOW) %>% 
  summarise(avg_LS = mean(LS_Impressions), 
            avg_C3 = mean(C3_Impressions)) %>% 
  plot_ly(x = ~DOW, colors = c("#31a354", "#3182bd")) %>%
  add_trace(y = ~avg_C3, color = "C3", type = "bar") %>%
  add_trace(y = ~avg_LS, color = "LS", type = "bar") %>% 
  layout(title = "Average C3 vs LS Impressions by Day of Week", 
         xaxis = list(title = "Day of Week"),
         yaxis = list(title = ""))
```

### Start Time

```{r}
data %>% filter(Season_num == 1) %>% 
  group_by(Start_Time) %>% 
  summarise(avg_LS = mean(LS_Impressions), 
            avg_C3 = mean(C3_Impressions)) %>% 
  plot_ly(x = ~Start_Time, colors = c("#31a354", "#3182bd")) %>%
  add_trace(y = ~avg_C3, color = "C3", type = "bar") %>%
  add_trace(y = ~avg_LS, color = "LS", type = "bar") %>% 
  layout(title = "Average C3 vs LS Impressions by Start Time", 
         xaxis = list(title = "Start Time"),
         yaxis = list(title = ""))
```

### Duration

```{r}
data %>% filter(Season_num == 1) %>%  
  group_by(Program_Duration) %>% 
  summarise(avg_LS = mean(LS_Impressions), 
            avg_C3 = mean(C3_Impressions)) %>% 
  plot_ly(x = ~Program_Duration, colors = c("#31a354", "#3182bd")) %>%
  add_trace(y = ~avg_C3, color = "C3", type = "bar") %>%
  add_trace(y = ~avg_LS, color = "LS", type = "bar") %>% 
  layout(title = "Average C3 vs LS Impressions by Program Duration", 
         xaxis = list(title = "Program Duration"),
         yaxis = list(title = ""))
```

### Cable Qtr

```{r}
data %>% filter(Season_num == 1) %>% 
  group_by(Cable_Qtr) %>% 
  summarise(avg_LS = mean(LS_Impressions), 
            avg_C3 = mean(C3_Impressions)) %>% 
  plot_ly(x = ~Cable_Qtr, colors = c("#31a354", "#3182bd")) %>%
  add_trace(y = ~avg_C3, color = "C3", type = "bar") %>%
  add_trace(y = ~avg_LS, color = "LS", type = "bar") %>% 
  layout(title = "Average C3 vs LS Impressions by Cable Quarter", 
         xaxis = list(title = "Program Duration"),
         yaxis = list(title = ""))
```

### Year

```{r}
data %>% filter(Season_num == 1) %>% 
  group_by(Broadcast_Year) %>% 
  summarise(avg_LS = mean(LS_Impressions), 
            avg_C3 = mean(C3_Impressions)) %>% 
  plot_ly(x = ~Broadcast_Year, colors = c("#31a354", "#3182bd")) %>%
  add_trace(y = ~avg_C3, color = "C3", type = "bar") %>%
  add_trace(y = ~avg_LS, color = "LS", type = "bar") %>% 
  layout(title = "Average C3 vs LS Impressions by Broadcast Year", 
         xaxis = list(title = "Broadcast Year"),
         yaxis = list(title = ""))
```

Column {.tabset}
---------------------------------------------------------------------------------------------------

### Network

```{r}
renderPlotly({
  data %>% 
    filter(Season_num == 1) %>%
    group_by(Date) %>% 
    mutate(avg_LS = mean(LS_Impressions), 
           avg_C3 = mean(C3_Impressions)) %>%
    filter(Network == as.character(input$network)) %>% 
    plot_ly(x = ~Date, colors = c("#31a354", "#3182bd")) %>%
    add_trace(y = ~avg_C3, type = "scatter", mode = "line", color = "C3") %>% 
    add_trace(y = ~avg_LS, type = "scatter", mode = "line", color = "LS") %>% 
    layout(title = paste("Avg C3 vs LS Over Time for", as.character(input$network)),
           margin = list(l = 80, 
                         r = 0, 
                         b = 100, 
                         t = 50), 
           xaxis = list(title = ""), 
           yaxis = list(title = ""))
})
```

### Genre

```{r}
renderPlotly({
  data %>% 
    filter(Season_num == 1) %>%
    group_by(Date) %>% 
    mutate(avg_LS = mean(LS_Impressions), 
           avg_C3 = mean(C3_Impressions)) %>%
    filter(Genre == as.character(input$genre)) %>% 
    plot_ly(x = ~Date, colors = c("#31a354", "#3182bd")) %>%
    add_trace(y = ~avg_C3, type = "scatter", mode = "line", color = "C3") %>% 
    add_trace(y = ~avg_LS, type = "scatter", mode = "line", color = "LS") %>% 
    layout(title = paste("Avg C3 vs LS Over Time for", as.character(input$genre)),
           margin = list(l = 80, 
                         r = 0, 
                         b = 100, 
                         t = 50), 
           xaxis = list(title = ""), 
           yaxis = list(title = ""))
})
```

### DOW

```{r}
renderPlotly({
  data %>% 
    filter(Season_num == 1) %>%
    group_by(Date) %>% 
    mutate(avg_LS = mean(LS_Impressions), 
           avg_C3 = mean(C3_Impressions)) %>%
    filter(DOW == as.character(input$dow)) %>% 
    plot_ly(x = ~Date, colors = c("#31a354", "#3182bd")) %>%
    add_trace(y = ~avg_C3, type = "scatter", mode = "line", color = "C3") %>% 
    add_trace(y = ~avg_LS, type = "scatter", mode = "line", color = "LS") %>% 
    layout(title = paste("Avg C3 vs LS Over Time for", as.character(input$dow)),
           margin = list(l = 80, 
                         r = 0, 
                         b = 100, 
                         t = 50), 
           xaxis = list(title = ""), 
           yaxis = list(title = ""))
})
```

### Start Time

```{r}
renderPlotly({
  data %>% 
    filter(Season_num == 1) %>%
    group_by(Date) %>% 
    mutate(avg_LS = mean(LS_Impressions), 
           avg_C3 = mean(C3_Impressions)) %>%
    filter(Start_Time == as.character(input$start)) %>% 
    plot_ly(x = ~Date, colors = c("#31a354", "#3182bd")) %>%
    add_trace(y = ~avg_C3, type = "scatter", mode = "line", color = "C3") %>% 
    add_trace(y = ~avg_LS, type = "scatter", mode = "line", color = "LS") %>% 
    layout(title = paste("Avg C3 vs LS Over Time for", as.character(input$start)),
           margin = list(l = 80, 
                         r = 0, 
                         b = 100, 
                         t = 50), 
           xaxis = list(title = ""), 
           yaxis = list(title = ""))
})
```

### Duration

```{r}
renderPlotly({
  data %>% 
    filter(Season_num == 1) %>%
    group_by(Date) %>% 
    mutate(avg_LS = mean(LS_Impressions), 
           avg_C3 = mean(C3_Impressions)) %>%
    filter(Program_Duration == as.character(input$duration)) %>% 
    plot_ly(x = ~Date, colors = c("#31a354", "#3182bd")) %>%
    add_trace(y = ~avg_C3, type = "scatter", mode = "line", color = "C3") %>% 
    add_trace(y = ~avg_LS, type = "scatter", mode = "line", color = "LS") %>% 
    layout(title = paste("Avg C3 vs LS Over Time for", as.character(input$duration)),
           margin = list(l = 80, 
                         r = 0, 
                         b = 100, 
                         t = 50), 
           xaxis = list(title = ""), 
           yaxis = list(title = ""))
})
```

### Cable Qtr

```{r}
renderPlotly({
  data %>% 
    filter(Season_num == 1) %>%
    group_by(Date) %>% 
    mutate(avg_LS = mean(LS_Impressions), 
           avg_C3 = mean(C3_Impressions)) %>%
    filter(Cable_Qtr == as.character(input$qtr)) %>% 
    plot_ly(x = ~Date, colors = c("#31a354", "#3182bd")) %>%
    add_trace(y = ~avg_C3, type = "scatter", mode = "line", color = "C3") %>% 
    add_trace(y = ~avg_LS, type = "scatter", mode = "line", color = "LS") %>% 
    layout(title = paste("Avg C3 vs LS Over Time for", as.character(input$qtr)),
           margin = list(l = 80, 
                         r = 0, 
                         b = 100, 
                         t = 50), 
           xaxis = list(title = ""), 
           yaxis = list(title = ""))
})
```

### Year

```{r}
renderPlotly({
  data %>% 
    filter(Season_num == 1) %>%
    group_by(Date) %>% 
    mutate(avg_LS = mean(LS_Impressions), 
           avg_C3 = mean(C3_Impressions)) %>%
    filter(Broadcast_Year == as.character(input$year)) %>% 
    plot_ly(x = ~Date, colors = c("#31a354", "#3182bd")) %>%
    add_trace(y = ~avg_C3, type = "scatter", mode = "line", color = "C3") %>% 
    add_trace(y = ~avg_LS, type = "scatter", mode = "line", color = "LS") %>% 
    layout(title = paste("Avg C3 vs LS Over Time for", as.character(input$year)),
           margin = list(l = 80, 
                         r = 0, 
                         b = 100, 
                         t = 50), 
           xaxis = list(title = ""), 
           yaxis = list(title = ""))
})
```

C3 vs LS by Show
===================================================================================================

Sidebar {.sidebar data-width=150}
---------------------------------------------------------------------------------------------------

```{r}
selectInput("showname", label = "Show:",
            choices = unique(data$Show_Name))
```

Column {.tabset}
---------------------------------------------------------------------------------------------------

### S1-S2

```{r}
renderPlotly({
  season2 <- data %>% filter(Show_Name == as.character(input$showname), Season_num == 2)
  data %>% 
    filter(Show_Name == as.character(input$showname)) %>% 
  plot_ly(x = ~cum_ep) %>%  
    add_trace(y = ~C3_Impressions, type = "scatter", mode = "line+markers", 
              color = "C3", line = list(color = "#31a354")) %>%
    add_trace(y = ~LS_Impressions, type = "scatter", mode = "line+markers", 
              color = "LS", line = list(color = "#3182bd")) %>%
    layout(title = paste("C3 vs LS Impressions for", as.character(input$showname)),
           yaxis = list(title = ""), 
           xaxis = list(title = "Cumulative Episode"),
           margin = list(l = 80, 
                         r = 0, 
                         b = 50, 
                         t = 50), 
           shapes = list(type = "line", 
                         x0 = ~min(season2$cum_ep), 
                         x1 = ~min(season2$cum_ep), 
                         xref = "x",
                         y0 = 0, 
                         y1 = 1,
                         yref = "paper",
                         line = list(dash = 'dot', width = 1)), 
           annotations = list(text = "Season 2",
                              font = list(family = "Arial", 
                                          color = "grey"),
                              x = ~min(season2$cum_ep),
                              xref = "x",
                              xanchor = "right",
                              y = 1,
                              yref = "paper",
                              textangle = 270,
                              showarrow = FALSE))
})
```

### S1

```{r}
renderPlotly({
  data %>% 
    filter(Show_Name == as.character(input$showname) & Season_num == 1) %>% 
  plot_ly(x = ~Episode_num) %>%  
    add_trace(y = ~C3_Impressions, type = "scatter", mode = "line+markers", 
              color = "C3", line = list(color = "#31a354")) %>%
    add_trace(y = ~LS_Impressions, type = "scatter", mode = "line+markers", 
              color = "LS", line = list(color = "#3182bd")) %>%
    layout(title = paste("C3 vs LS Impressions for", 
                         as.character(input$showname), 
                         "Season 1"),
           yaxis = list(title = ""), 
           xaxis = list(title = "Episode"),
           margin = list(l = 80, 
                         r = 0, 
                         b = 50, 
                         t = 50))
})
```

### S2

```{r}
renderPlotly({
  data %>% 
    filter(Show_Name == as.character(input$showname) & Season_num == 2) %>% 
  plot_ly(x = ~Episode_num) %>%  
    add_trace(y = ~C3_Impressions, type = "scatter", mode = "line+markers", 
              color = "C3", line = list(color = "#31a354")) %>%
    add_trace(y = ~LS_Impressions, type = "scatter", mode = "line+markers", 
              color = "LS", line = list(color = "#3182bd")) %>%
    layout(title = paste("C3 vs LS Impressions for", 
                         as.character(input$showname), 
                         "Season 1"),
           yaxis = list(title = ""), 
           xaxis = list(title = "Episode"),
           margin = list(l = 80, 
                         r = 0, 
                         b = 50, 
                         t = 50))
})
```

Column {.tabset data-width=300, data-height=800}
---------------------------------------------------------------------------------------------------

### S1-S2

```{r}
data %>% 
  group_by(Show_Name) %>% summarise(avg_LS = mean(LS_Impressions), 
                                    avg_C3 = mean(C3_Impressions)) %>% 
  plot_ly(y = ~Show_Name, colors = c("#31a354", "#3182bd")) %>%
  add_trace(x = ~avg_C3, color = "C3", type = "bar") %>%
  add_trace(x = ~avg_LS, color = "LS", type = "bar") %>% 
  layout(title = "Average C3 vs LS Impressions by Show", 
         xaxis = list(title = ""),
         yaxis = list(title = ""),
         margin = list(l = 170))
```

### S1

```{r}
data %>% 
  group_by(Show_Name) %>% filter(Season_num == 1) %>% 
  summarise(avg_LS = mean(LS_Impressions), 
            avg_C3 = mean(C3_Impressions)) %>% 
  plot_ly(y = ~Show_Name, colors = c("#31a354", "#3182bd")) %>%
  add_trace(x = ~avg_C3, color = "C3", type = "bar") %>%
  add_trace(x = ~avg_LS, color = "LS", type = "bar") %>% 
  layout(title = "Average C3 vs LS Impressions by Show", 
         xaxis = list(title = ""),
         yaxis = list(title = ""),
         margin = list(l = 170))
```

### S2

```{r}
data %>% 
  group_by(Show_Name) %>% filter(Season_num == 2) %>%
  summarise(avg_LS = mean(LS_Impressions), 
            avg_C3 = mean(C3_Impressions)) %>% 
  plot_ly(y = ~Show_Name, colors = c("#31a354", "#3182bd")) %>%
  add_trace(x = ~avg_C3, color = "C3", type = "bar") %>%
  add_trace(x = ~avg_LS, color = "LS", type = "bar") %>% 
  layout(title = "Average C3 vs LS Impressions by Show", 
         xaxis = list(title = ""),
         yaxis = list(title = ""),
         margin = list(l = 170))
```

Data Tables
===================================================================================================

Column {.tabset}
---------------------------------------------------------------------------------------------------

### By Episode

```{r}
renderDataTable(data, options = list(scrollY = '400px', scrollX = '700px'))
```


### Season Stats

```{r}
renderDataTable(stats_by_season, options = list(scrollY = '400px', scrollX = '700px'))
```

### S1 C3 Raw Clusters

```{r}
renderDataTable({
  data %>% 
    filter(Season_num == 1) %>% 
    group_by(C3_raw_cluster) %>% 
    summarise(unique_DOW = length(unique(DOW)), 
              unique_start = length(unique(Start_Time)), 
              unique_network = length(unique(Network)), 
              unique_broadcast_year = length(unique(Broadcast_Year)), 
              unique_genre = length(unique(Genre)), 
              unique_duration = length(unique(Program_Duration)), 
              higher_imps_by_ep = ifelse(((sum(higher_imps == "C3")) > sum(higher_imps == "LS")), 
                                           "C3", "LS"), 
              avg_C3 = mean(C3_Impressions), 
              avg_LS = mean(LS_Impressions))
})
```

### S1 LS Raw Clusters

```{r}
renderDataTable({
  data %>% 
    filter(Season_num == 1) %>% 
    group_by(LS_raw_cluster) %>% 
    summarise(unique_DOW = length(unique(DOW)), 
              unique_start = length(unique(Start_Time)), 
              unique_network = length(unique(Network)), 
              unique_broadcast_year = length(unique(Broadcast_Year)), 
              unique_genre = length(unique(Genre)), 
              unique_duration = length(unique(Program_Duration)), 
              higher_imps_by_ep = ifelse(((sum(higher_imps == "C3")) > sum(higher_imps == "LS")), 
                                           "C3", "LS"), 
              avg_C3 = mean(C3_Impressions), 
              avg_LS = mean(LS_Impressions))
})
```

Cluster Plots
===================================================================================================

Column 
---------------------------------------------------------------------------------------------------

### C3 Raw

```{r}
renderPlotly({
  clusters_C3_raw %>%  
    plot_ly(x = ~period, y = ~dct_values, 
            color = ~Show_Name, yaxis = ~paste0('y', cluster_kmeans_5), 
            legendgroup = ~cluster_kmeans_5) %>% 
    add_lines() %>% 
    subplot(nrows = 5, shareX = TRUE) %>% 
    layout(showlegend = TRUE, 
           title = "S1 with 5 K-Means Clusters and S2 Trends (C3)", 
           margin = list(l = 50, 
                         r = 50, 
                         b = 50, 
                         t = 125), 
           xaxis = list(title = ""))
})
```

Column 
---------------------------------------------------------------------------------------------------

### LS Raw

```{r}
renderPlotly({
  clusters_LS_raw %>% 
    plot_ly(x = ~period, y = ~dct_values, 
            color = ~Show_Name, yaxis = ~paste0('y', cluster_kmeans_5), 
            legendgroup = ~cluster_kmeans_5) %>% 
    add_lines() %>% 
    subplot(nrows = 5, shareX = TRUE) %>% 
    layout(showlegend = TRUE, 
           title = "S1 with 5 K-Means Clusters and S2 Trends (LS)", 
           margin = list(l = 50, 
                         r = 50, 
                         b = 50, 
                         t = 125), 
           xaxis = list(title = ""))
})
```

