---
author: "Best Clusters by Schedule Variables"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    source_code: embed
---

```{r}
#############################################################
#
# Inputs: s1_s2_data.csv, dct_C3_raw.csv, dct_C3_growth.csv, 
#         dct_C3_raw_cont.csv, dct_C3_growth_cont.csv, 
#         s1_shows_best_clusters_and_matches.csv 
#
# Purpose: Clusters as raw impressions, growth, and
#          normalized colored by Day of Week (DOW),
#          AND Time of Day (TOD) for pattern observation
#
#############################################################
```

```{r}
library(plyr)
library(dplyr)
library(ggplot2)
library(plotly)
library(scales)
```

```{r}
df <- read.csv("s1_s2_data.csv") %>% select(-X) %>% filter(Episode_num < 15)
df_dct <- read.csv("dct_C3_raw_cont.csv") %>% select(-X)
df_dct_s1 <- read.csv("dct_C3_raw.csv") %>% select(-X)
df_dct_growth <- read.csv("dct_C3_growth_cont.csv") %>% select(-X)
df_dct_growth_s1 <- read.csv("dct_C3_growth.csv") %>% select(-X)
s1_shows_best_clusters<- read.csv("s1_shows_best_clusters.csv") %>% select(-X)
matches_only <- read.csv("s1_shows_best_clusters_and_matches.csv") %>% 
  select(Show_Name, C3_raw_best_matches, C3_raw_best_matches_S2, 
         C3_growth_best_matches, C3_growth_best_matches_S2)

df <- merge(df, s1_shows_best_clusters)
df_dct <- merge(df_dct, s1_shows_best_clusters)
df_dct_s1 <- merge(df_dct_s1, s1_shows_best_clusters)
df_dct_growth <- merge(df_dct_growth, s1_shows_best_clusters)
df_dct_growth_s1 <- merge(df_dct_growth_s1, s1_shows_best_clusters)

df <- merge(df, matches_only)
df_dct <- merge(df_dct, matches_only)
df_dct_s1 <- merge(df_dct_s1, matches_only)
df_dct_growth <- merge(df_dct_growth, matches_only)
df_dct_growth_s1 <- merge(df_dct_growth_s1, matches_only)
```

```{r}
my_theme <-  theme(panel.background = element_blank(), 
                   panel.grid.major = element_line(color = "#d8d8d8", linetype = "dotted"), 
                   panel.grid.major.x = element_blank(), 
                   plot.title = element_text(hjust = 0.5),
                   axis.title.y = element_blank(),
                   axis.line.y = element_blank(),
                   axis.ticks.y = element_blank(),
                   axis.line.x = element_line(color = "#d8d8d8", linetype = "dashed"),
                   strip.background = element_blank())
```

```{r}
a <- df %>% filter(is.na(C3_raw_cluster) == F) %>% select(Show_Name, Start_Time, Season_num) %>%
  group_by(Show_Name, Season_num, Start_Time) %>% count()
```

Raw Clusters
============================================== 

Column {data-height=2000} {.tabset}
-------------------------------------

###Raw Impressions. Start Time 

```{r, fig.height=10}
C3_raw <- ggplot(df %>% filter(is.na(C3_raw_cluster) == F)) +
  geom_line(aes(x = Episode_num, y = C3_Impressions, group = Show_Name, color = Start_Time)) +
  labs(x = "Episode Number") +
  scale_y_continuous(labels = comma) +
  coord_cartesian(ylim = c(0, 1500000), xlim = c(1, 13)) +
  facet_grid(C3_raw_cluster ~ Season_num, scale = "free_y") +
  theme(panel.spacing = unit(0, "lines")) +
  my_theme

ggplotly(C3_raw) %>% 
  layout(title = "C3 Impressions, S1-S2. Start Time",
         autosize = FALSE, width = 650, height = 1000, 
         margin = list(l = 0, 
                       r = 50, 
                       b = 100, 
                       t = 50))
```

###Raw Impressions. DOW 

```{r, fig.height=10}
C3_raw <- ggplot(df %>% filter(is.na(C3_raw_cluster) == F)) +
  geom_line(aes(x = Episode_num, y = C3_Impressions, group = Show_Name, color = DOW)) +
  labs(x = "Episode Number") +
  scale_y_continuous(labels = comma) +
  coord_cartesian(ylim = c(0, 1500000), xlim = c(1, 13)) +
  facet_grid(C3_raw_cluster ~ Season_num, scale = "free_y") +
  theme(panel.spacing = unit(0, "lines")) +
  my_theme

ggplotly(C3_raw) %>% 
  layout(title = "C3 Impressions, S1-S2. DOW",
         autosize = FALSE, width = 650, height = 1000, 
         margin = list(l = 0, 
                       r = 50, 
                       b = 100, 
                       t = 50))
```

Column {data-height=2000} {.tabset}
-------------------------------------

###Growth. Start Time

```{r, fig.height=10}
C3_raw <- ggplot(df %>% filter(is.na(C3_raw_cluster) == F)) +
  geom_line(aes(x = Episode_num, y = C3_Growth, group = Show_Name, color = Start_Time)) +
  labs(x = "Episode Number") +
  scale_y_continuous(labels = comma) +
  coord_cartesian(ylim = c(0, 3), xlim = c(1, 13)) +
  facet_grid(C3_raw_cluster ~ Season_num) +
  theme(panel.spacing = unit(0, "lines")) +
  my_theme

ggplotly(C3_raw) %>% 
  layout(title = "Growth, S1-S2. Start Time",
         autosize = FALSE, width = 650, height = 1000, 
         margin = list(l = 0, 
                       r = 50, 
                       b = 100, 
                       t = 50))
```

###Growth. DOW

```{r, fig.height=10}
C3_raw <- ggplot(df %>% filter(is.na(C3_raw_cluster) == F)) +
  geom_line(aes(x = Episode_num, y = C3_Growth, group = Show_Name, color = DOW)) +
  labs(x = "Episode Number") +
  scale_y_continuous(labels = comma) +
  coord_cartesian(ylim = c(0, 3), xlim = c(1, 13)) +
  facet_grid(C3_raw_cluster ~ Season_num) +
  theme(panel.spacing = unit(0, "lines")) +
  my_theme

ggplotly(C3_raw) %>% 
  layout(title = "Growth, S1-S2. DOW",
         autosize = FALSE, width = 650, height = 1000, 
         margin = list(l = 0, 
                       r = 50, 
                       b = 100, 
                       t = 50))
```

Column {data-height=2000} {.tabset}
-------------------------------------

### Normalized Impressions. S1

```{r, fig.height=10}
C3_raw <- ggplot(df_dct_s1 %>% filter(is.na(C3_raw_cluster) == F, Season_num == 1)) +
  geom_line(aes(x = period, y = dct_values, color = Show_Name)) +
  scale_y_continuous(labels = comma) +
  facet_wrap(~C3_raw_cluster, nrow = 5) +
  my_theme 

ggplotly(C3_raw) %>% 
  layout(title = "C3 Normalized Impressions. S1.",
         autosize = FALSE, width = 650, height = 1000, 
         margin = list(l = 0, 
                       r = 50, 
                       b = 100, 
                       t = 50))
```

### Normalized Impressions. Best Match S2 

```{r, fig.height=10}
C3_raw <- ggplot(df_dct %>% filter(is.na(C3_raw_cluster) == F, 
                                   period <= 50 | period > 50 & !is.na(C3_raw_best_matches_S2))) +
  geom_line(aes(x = period, y = dct_values, color = Show_Name)) +
  scale_y_continuous(labels = comma) +
  facet_wrap(~C3_raw_cluster, nrow = 5) +
  my_theme 

ggplotly(C3_raw) %>% 
  layout(title = "C3 Normalized Impressions, S1-S2. Best Match S2",
         autosize = FALSE, width = 650, height = 1000, 
         margin = list(l = 0, 
                       r = 50, 
                       b = 100, 
                       t = 50))
```

Growth Clusters
============================================== 

Column {data-height=2000} {.tabset}
-------------------------------------

###Growth. Start Time

```{r, fig.height=10}
C3_raw <- ggplot(df %>% filter(is.na(C3_growth_cluster) == F)) +
  geom_line(aes(x = Episode_num, y = C3_Growth, group = Show_Name, color = Start_Time)) +
  labs(x = "Episode Number") +
  scale_y_continuous(labels = comma) +
  coord_cartesian(ylim = c(0, 3), xlim = c(1, 13)) +
  facet_grid(C3_growth_cluster ~ Season_num) +
  theme(panel.spacing = unit(0, "lines")) +
  my_theme

ggplotly(C3_raw) %>% 
  layout(title = "Growth, S1-S2. Start Time",
         autosize = FALSE, width = 650, height = 1000, 
         margin = list(l = 0, 
                       r = 50, 
                       b = 100, 
                       t = 50))
```

###Growth. DOW

```{r, fig.height=10}
C3_raw <- ggplot(df %>% filter(is.na(C3_growth_cluster) == F)) +
  geom_line(aes(x = Episode_num, y = C3_Growth, group = Show_Name, color = DOW)) +
  labs(x = "Episode Number") +
  scale_y_continuous(labels = comma) +
  coord_cartesian(ylim = c(0, 3), xlim = c(1, 13)) +
  facet_grid(C3_growth_cluster ~ Season_num) +
  theme(panel.spacing = unit(0, "lines")) +
  my_theme

ggplotly(C3_raw) %>% 
  layout(title = "Growth, S1-S2. DOW",
         autosize = FALSE, width = 650, height = 1000, 
         margin = list(l = 0, 
                       r = 50, 
                       b = 100, 
                       t = 50))
```

Column {data-height=2000} {.tabset}
-------------------------------------

###Raw Impressions. Start Time 

```{r, fig.height=10}
C3_raw <- ggplot(df %>% filter(is.na(C3_growth_cluster) == F)) +
  geom_line(aes(x = Episode_num, y = C3_Impressions, group = Show_Name, color = Start_Time)) +
  labs(x = "Episode Number") +
  scale_y_continuous(labels = comma) +
  coord_cartesian(ylim = c(0, 1500000), xlim = c(1, 13)) +
  facet_grid(C3_growth_cluster ~ Season_num, scale = "free_y") +
  theme(panel.spacing = unit(0, "lines")) +
  my_theme

ggplotly(C3_raw) %>% 
  layout(title = "C3 Impressions, S1-S2. Start Time",
         autosize = FALSE, width = 650, height = 1000, 
         margin = list(l = 0, 
                       r = 50, 
                       b = 100, 
                       t = 50))
```

###Raw Impressions. DOW 

```{r, fig.height=10}
C3_raw <- ggplot(df %>% filter(is.na(C3_growth_cluster) == F)) +
  geom_line(aes(x = Episode_num, y = C3_Impressions, group = Show_Name, color = DOW)) +
  labs(x = "Episode Number") +
  scale_y_continuous(labels = comma) +
  coord_cartesian(ylim = c(0, 1500000), xlim = c(1, 13)) +
  facet_grid(C3_growth_cluster ~ Season_num, scale = "free_y") +
  theme(panel.spacing = unit(0, "lines")) +
  my_theme

ggplotly(C3_raw) %>% 
  layout(title = "C3 Impressions, S1-S2. DOW",
         autosize = FALSE, width = 650, height = 1000, 
         margin = list(l = 0, 
                       r = 50, 
                       b = 100, 
                       t = 50))
```

Column {data-height=2000} {.tabset}
-------------------------------------

### Normalized Growth. S1

```{r, fig.height=10}
C3_raw <- ggplot(df_dct_growth_s1 %>% filter(is.na(C3_growth_cluster) == F, Season_num == 1)) +
  geom_line(aes(x = period, y = dct_values, color = Show_Name)) +
  scale_y_continuous(labels = comma) +
  facet_wrap(~C3_growth_cluster, nrow = 5) +
  my_theme 

ggplotly(C3_raw) %>% 
  layout(title = "C3 Normalized growth. S1.",
         autosize = FALSE, width = 650, height = 1000, 
         margin = list(l = 0, 
                       r = 50, 
                       b = 100, 
                       t = 50))
```

### Normalized Impressions. Best Match S2 

```{r, fig.height=10}
C3_raw <- ggplot(df_dct_growth %>% filter(is.na(C3_growth_cluster) == F, 
                                          period <= 50 | period > 50 & !is.na(C3_growth_best_matches_S2))) +
  geom_line(aes(x = period, y = dct_values, color = Show_Name)) +
  scale_y_continuous(labels = comma) +
  facet_wrap(~C3_growth_cluster, nrow = 5) +
  my_theme 

ggplotly(C3_raw) %>% 
  layout(title = "C3 Normalized growth, S1-S2. Best Match S2",
         autosize = FALSE, width = 650, height = 1000, 
         margin = list(l = 0, 
                       r = 50, 
                       b = 100, 
                       t = 50))
```
