---
title: "CENT S1 Clusters"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    source_code: embed
---

```{r}
library(dplyr)
library(plotly)
```

S1 Clusters
===================================== 

Column {data-height=1800}
-------------------------------------

###

```{r, fig.height=6}
kmeans_C3_raw_s1_5cl <- read.csv("kmeans_C3_raw_s1_5cl.csv") 

kmeans_C3_raw_s1_5cl_plot <- kmeans_C3_raw_s1_5cl %>% 
  filter(Season_num == 1) %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster_kmeans_5, nrow = 3) +  
  theme(axis.title.x = element_blank(), 
        axis.title.y = element_blank())

ggplotly(kmeans_C3_raw_s1_5cl_plot) %>% 
  layout(title = "S1 with 5 K-Means Clusters (C3)", 
         autosize = FALSE, width = 750, height = 600, 
         margin = list(l = 50, 
                       r = 50, 
                       b = 50, 
                       t = 125), 
         xaxis = list(title = ""))
```

###

```{r, fig.height=6}
kmeans_C3_growth_s1_4cl <- read.csv("kmeans_C3_growth_s1_4cl.csv")

kmeans_C3_growth_s1_4cl_plot <- kmeans_C3_growth_s1_4cl %>% 
  filter(Season_num == 1) %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster_kmeans_4) +  
  theme(axis.title.x = element_blank(), 
        axis.title.y = element_blank())

ggplotly(kmeans_C3_growth_s1_4cl_plot) %>% 
  layout(title = "S1 with 4 K-Means Clusters (C3 Growth)", 
         autosize = FALSE, width = 750, height = 600, 
         margin = list(l = 50, 
                       r = 50, 
                       b = 50, 
                       t = 125), 
         xaxis = list(title = ""))
```

###

```{r, fig.height=6}
kmeans_C3_growth_s1_5cl <- read.csv("kmeans_C3_growth_s1_5cl.csv")

kmeans_C3_growth_s1_5cl_plot <- kmeans_C3_growth_s1_5cl %>% 
  filter(Season_num == 1) %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster_kmeans_5, nrow = 3) +  
  theme(axis.title.x = element_blank(), 
        axis.title.y = element_blank())

ggplotly(kmeans_C3_growth_s1_5cl_plot) %>% 
  layout(title = "S1 with 5 K-Means Clusters (C3 Growth)", 
         autosize = FALSE, width = 750, height = 600, 
         margin = list(l = 50, 
                       r = 50, 
                       b = 50, 
                       t = 125), 
         xaxis = list(title = ""))
```

Column {data-height=1800}
-------------------------------------

###

```{r, fig.height=6}
kmeans_LS_raw_s1_5cl <- read.csv("kmeans_LS_raw_s1_5cl.csv")

kmeans_LS_raw_s1_5cl_plot <- kmeans_LS_raw_s1_5cl %>%
  filter(Season_num == 1) %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster_kmeans_5, nrow = 3) +  
  theme(axis.title.x = element_blank(), 
        axis.title.y = element_blank())

ggplotly(kmeans_LS_raw_s1_5cl_plot) %>% 
  layout(title = "S1 with 5 K-Means Clusters (LS)", 
         autosize = FALSE, width = 650, height = 600, 
         margin = list(l = 50, 
                       r = 50, 
                       b = 50, 
                       t = 125), 
         xaxis = list(title = ""))
```

###

```{r, fig.height=6}
kmeans_LS_growth_s1_5cl <- read.csv("kmeans_LS_growth_s1_5cl.csv")

kmeans_LS_growth_s1_5cl_plot <- kmeans_LS_growth_s1_5cl %>%
  filter(Season_num == 1) %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster_kmeans_5, nrow = 3) +  
  theme(axis.title.x = element_blank(), 
        axis.title.y = element_blank())

ggplotly(kmeans_LS_growth_s1_5cl_plot) %>% 
  layout(title = "S1 with 5 K-Means Clusters (LS Growth)", 
         autosize = FALSE, width = 650, height = 600, 
         margin = list(l = 50, 
                       r = 50, 
                       b = 50, 
                       t = 125), 
         xaxis = list(title = ""))
```

C3 & LS Impressions
============================================== 

Column {data-height=850} {.tabset}
-------------------------------------

### S1 Clusters & S2 Trends

```{r, fig.height=8.5}
kmeans_C3_raw_s1_5cl_s2trends <- read.csv("kmeans_C3_raw_s1_5cl_s2trends.csv")

kmeans_C3_raw_s1_5cl_s2trends_plot <- plot_ly(kmeans_C3_raw_s1_5cl_s2trends, 
        x = ~period, 
        y = ~dct_values, 
        color = ~Show_Name,
        yaxis = ~paste0('y', cluster_kmeans_5), 
        legendgroup = ~cluster_kmeans_5) %>% 
  add_lines() %>% 
  subplot(nrows = 5, shareX = TRUE) %>% 
  layout(showlegend = TRUE, 
         title = "S1 with 5 K-Means Clusters & S2 Trends (C3)", 
         autosize = FALSE, width = 650, height = 800, 
         margin = list(l = 50, 
                       r = 50, 
                       b = 50, 
                       t = 125), 
         xaxis = list(title = ""))

kmeans_C3_raw_s1_5cl_s2trends_plot
```

### S1-S2 Trends by S1 Clusters

```{r, fig.height=8.5}
kmeans_C3_raw_s1_5cl_cont_trends <- read.csv("kmeans_C3_raw_s1_5cl_cont_trends.csv") 

kmeans_C3_raw_s1_5cl_cont_trends_plot <- plot_ly(kmeans_C3_raw_s1_5cl_cont_trends, 
        x = ~period, 
        y = ~dct_values, 
        color = ~Show_Name,
        yaxis = ~paste0('y', s1_cluster), 
        legendgroup = ~s1_cluster) %>% 
  add_lines() %>% 
  subplot(nrows = 5, shareX = TRUE) %>% 
  layout(showlegend = TRUE, 
         title = "S1-S2 Clustered on S1 Clusters (C3 Raw)", 
         autosize = FALSE, width = 650, height = 800, 
         margin = list(l = 50, 
                       r = 50, 
                       b = 50, 
                       t = 125), 
         xaxis = list(title = ""))

kmeans_C3_raw_s1_5cl_cont_trends_plot
```

Column {data-height=850} {.tabset}
-------------------------------------

### S1 Clusters & S2 Trends

```{r, fig.height=8.5}
kmeans_LS_raw_s1_5cl_s2trends <- read.csv("kmeans_LS_raw_s1_5cl_s2trends.csv")

kmeans_LS_raw_s1_5cl_s2trends_plot <- plot_ly(kmeans_LS_raw_s1_5cl_s2trends, 
        x = ~period, 
        y = ~dct_values, 
        color = ~Show_Name,
        yaxis = ~paste0('y', cluster_kmeans_5), 
        legendgroup = ~cluster_kmeans_5) %>% 
  add_lines() %>% 
  subplot(nrows = 5, shareX = TRUE) %>% 
  layout(showlegend = TRUE, 
         title = "S1 with 5 K-Means Clusters & S2 Trends (LS)", 
         autosize = FALSE, width = 650, height = 800, 
         margin = list(l = 50, 
                       r = 50, 
                       b = 50, 
                       t = 125), 
         xaxis = list(title = ""))

kmeans_LS_raw_s1_5cl_s2trends_plot
```

### S1-S2 Trends by S1 Clusters

```{r, fig.height=8.5}
kmeans_LS_raw_s1_5cl_cont_trends <- read.csv("kmeans_LS_raw_s1_5cl_cont_trends.csv") 

kmeans_LS_raw_s1_5cl_cont_trends_plot <- plot_ly(kmeans_LS_raw_s1_5cl_cont_trends, 
        x = ~period, 
        y = ~dct_values, 
        color = ~Show_Name,
        yaxis = ~paste0('y', s1_cluster), 
        legendgroup = ~s1_cluster) %>% 
  add_lines() %>% 
  subplot(nrows = 5, shareX = TRUE) %>% 
  layout(showlegend = TRUE, 
         title = "S1-S2 Clustered on S1 Clusters (LS Raw)", 
         autosize = FALSE, width = 650, height = 800, 
         margin = list(l = 50, 
                       r = 50, 
                       b = 50, 
                       t = 125), 
         xaxis = list(title = ""))

kmeans_LS_raw_s1_5cl_cont_trends_plot
```

C3 & LS Growth
============================================== 

Column {data-height=850} {.tabset}
-------------------------------------

### S1 Clusters & S2 Trends (4)

```{r, fig.height=8.5}
kmeans_C3_growth_s1_4cl_s2trends <- read.csv("kmeans_C3_growth_s1_4cl_s2trends.csv")

kmeans_C3_growth_s1_4cl_s2trends_plot <- plot_ly(kmeans_C3_growth_s1_4cl_s2trends, 
        x = ~period, 
        y = ~dct_values, 
        color = ~Show_Name,
        yaxis = ~paste0('y', cluster_kmeans_4), 
        legendgroup = ~cluster_kmeans_4) %>% 
  add_lines() %>% 
  subplot(nrows = 4, shareX = TRUE) %>% 
  layout(showlegend = TRUE, 
         title = "S1 with 4 K-Means Clusters & S2 Trends (C3 Growth)", 
         autosize = FALSE, width = 650, height = 800, 
         margin = list(l = 50, 
                       r = 50, 
                       b = 50, 
                       t = 125), 
         xaxis = list(title = ""))

kmeans_C3_growth_s1_4cl_s2trends_plot
```

### S1-S2 Trends by S1 Clusters (4)

```{r, fig.height=8.5}
kmeans_C3_growth_s1_4cl_cont_trends <- read.csv("kmeans_C3_growth_s1_4cl_cont_trends.csv") 

kmeans_C3_growth_s1_4cl_cont_trends_plot <- plot_ly(kmeans_C3_growth_s1_4cl_cont_trends, 
        x = ~period, 
        y = ~dct_values, 
        color = ~Show_Name,
        yaxis = ~paste0('y', s1_cluster), 
        legendgroup = ~s1_cluster) %>% 
  add_lines() %>% 
  subplot(nrows = 5, shareX = TRUE) %>% 
  layout(showlegend = TRUE, 
         title = "S1-S2 Clustered on S1 Clusters (C3 Growth)", 
         autosize = FALSE, width = 650, height = 800, 
         margin = list(l = 50, 
                       r = 50, 
                       b = 50, 
                       t = 125), 
         xaxis = list(title = ""))

kmeans_C3_growth_s1_4cl_cont_trends_plot
```

### S1 Clusters & S2 Trends (5)

```{r, fig.height=8.5}
kmeans_C3_growth_s1_5cl_s2trends <- read.csv("kmeans_C3_growth_s1_5cl_s2trends.csv")

kmeans_C3_growth_s1_5cl_s2trends_plot <- plot_ly(kmeans_C3_growth_s1_5cl_s2trends, 
        x = ~period, 
        y = ~dct_values, 
        color = ~Show_Name,
        yaxis = ~paste0('y', cluster_kmeans_5), 
        legendgroup = ~cluster_kmeans_5) %>% 
  add_lines() %>% 
  subplot(nrows = 5, shareX = TRUE) %>% 
  layout(showlegend = TRUE, 
         title = "S1 with 5 K-Means Clusters & S2 Trends (C3 Growth)", 
         autosize = FALSE, width = 650, height = 800, 
         margin = list(l = 50, 
                       r = 50, 
                       b = 50, 
                       t = 125), 
         xaxis = list(title = ""))

kmeans_C3_growth_s1_5cl_s2trends_plot
```

### S1-S2 Trends by S1 Clusters (5)

```{r, fig.height=8.5}
kmeans_C3_growth_s1_5cl_cont_trends <- read.csv("kmeans_C3_growth_s1_5cl_cont_trends.csv") 

kmeans_C3_growth_s1_5cl_cont_trends_plot <- plot_ly(kmeans_C3_growth_s1_5cl_cont_trends, 
        x = ~period, 
        y = ~dct_values, 
        color = ~Show_Name,
        yaxis = ~paste0('y', s1_cluster), 
        legendgroup = ~s1_cluster) %>% 
  add_lines() %>% 
  subplot(nrows = 5, shareX = TRUE) %>% 
  layout(showlegend = TRUE, 
         title = "S1-S2 Clustered on S1 Clusters (C3 Growth)", 
         autosize = FALSE, width = 650, height = 800, 
         margin = list(l = 50, 
                       r = 50, 
                       b = 50, 
                       t = 125), 
         xaxis = list(title = ""))

kmeans_C3_growth_s1_5cl_cont_trends_plot
```

Column {data-height=850} {.tabset}
-------------------------------------

### S1 Clusters & S2 Trends

```{r, fig.height=8.5}
kmeans_LS_growth_s1_5cl_s2trends <- read.csv("kmeans_LS_growth_s1_5cl_s2trends.csv") 

kmeans_LS_growth_s1_5cl_s2trends_plot <- plot_ly(kmeans_LS_growth_s1_5cl_s2trends, 
        x = ~period, 
        y = ~dct_values, 
        color = ~Show_Name,
        yaxis = ~paste0('y', cluster_kmeans_5), 
        legendgroup = ~cluster_kmeans_5) %>% 
  add_lines() %>% 
  subplot(nrows = 5, shareX = TRUE) %>% 
  layout(showlegend = TRUE, 
         title = "S1 with 5 K-Means Clusters & S2 Trends (LS Growth)", 
         autosize = FALSE, width = 650, height = 800, 
         margin = list(l = 50, 
                       r = 50, 
                       b = 50, 
                       t = 125), 
         xaxis = list(title = ""))

kmeans_LS_growth_s1_5cl_s2trends_plot
```

### S1-S2 Trends by S1 Clusters

```{r, fig.height=8.5}
kmeans_LS_growth_s1_5cl_cont_trends <- read.csv("kmeans_LS_growth_s1_5cl_cont_trends.csv") 

kmeans_LS_growth_s1_5cl_cont_trends_plot <- plot_ly(kmeans_LS_growth_s1_5cl_cont_trends, 
        x = ~period, 
        y = ~dct_values, 
        color = ~Show_Name,
        yaxis = ~paste0('y', s1_cluster), 
        legendgroup = ~s1_cluster) %>% 
  add_lines() %>% 
  subplot(nrows = 5, shareX = TRUE) %>% 
  layout(showlegend = TRUE, 
         title = "S1-S2 Clustered on S1 Clusters (LS Growth)", 
         autosize = FALSE, width = 650, height = 800, 
         margin = list(l = 50, 
                       r = 50, 
                       b = 50, 
                       t = 125), 
         xaxis = list(title = ""))

kmeans_LS_growth_s1_5cl_cont_trends_plot
```

