---
title: "Exploratory Plots for Normalized C3"
output:
  html_notebook: default
  html_document: default
---

```{r}
##################################################################################
# inputs: dct_C3_raw.csv, dct_C3_growth.csv
#
# purpose: Exploratory plots for raw and growth normalized C3 impressions
##################################################################################
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, error = FALSE, echo = FALSE)
```

```{r}
library(dplyr)
library(ggplot2)
library(plotly)
library(scales)
library(purrr)
library(tidyr)
```

# Raw C3 Impressions, Normalized

Read data
```{r}
df_with_dct <- read.csv("dct_C3_raw.csv")
df <- df_with_dct %>% group_by(Network, Show_Name, Season_num) %>% 
  mutate(growth = lag(dct_values, 1) / dct_values)
```

Define ggplot theme
```{r}
my_theme <-  theme(panel.background = element_blank(), 
                   panel.grid.major = element_line(color = "#d8d8d8", linetype = "dotted"), 
                   panel.grid.major.x = element_blank(), 
                   plot.title = element_text(hjust = 0.5),
                   axis.title.x = element_blank(), 
                   axis.title.y = element_blank(),
                   axis.line.y = element_blank(),
                   axis.ticks.y = element_blank(),
                   axis.line.x = element_line(color = "#d8d8d8", linetype = "dashed"),
                   strip.background = element_blank())
```

## DCT Values Trends

```{r}
DCT_trends <- ggplotly(ggplot(df %>% filter(Season_num < 3)) + 
                         geom_line(aes(x = period, y = dct_values, color = Show_Name), 
                                   alpha = 0.6) + scale_colour_hue(h = c(180, 270)) + 
                         geom_line(data = df %>% filter (Season_num < 3, Network == "BRVO") %>% 
                                     group_by(Network, Season_num, period) %>% 
                                     summarise(avg = mean(dct_values)), 
                                   aes(x = period, y = avg, linetype = Network), 
                                   size = 1.2, color = "#7a0177") +
                         geom_line(data = df %>% filter (Season_num < 3, Network == "ENT") %>% 
                                     group_by(Network, Season_num, period) %>% 
                                     summarise(avg = mean(dct_values)),
                                   aes(x = period, y = avg, linetype = Network), 
                                   size = 1.2, color = "#ae017e") +
                         geom_line(data = df %>% filter (Season_num < 3, Network == "SYFY") %>% 
                                     group_by(Network, Season_num, period) %>% 
                                     summarise(avg = mean(dct_values)),
                                   aes(x = period, y = avg, linetype = Network), 
                                   size = 1.2, color = "#dd3497") +
                         geom_line(data = df %>% filter (Season_num < 3, Network == "USA") %>% 
                                     group_by(Network, Season_num, period) %>% 
                                     summarise(avg = mean(dct_values)),
                                   aes(x = period, y = avg, linetype = Network), 
                                   size = 1.2, color = "#f768a1") + 
                         geom_line(data = df %>% filter (Season_num < 3) %>% 
                                     group_by(Season_num, period) %>% 
                                     summarise(avg = mean(dct_values)), 
                                   aes(x = period, y = avg, color = Show_Name), 
                                   color = "black", linetype = "dashed", size = 1.3) + 
                         facet_wrap(~Season_num, nrow = 2) + my_theme) %>% 
  layout(title = "DCT Value Trends for All Shows and Networks (C3)", 
         autosize = FALSE, width = 650, height = 800, 
         margin = list(l = 50, 
                       r = 50, 
                       b = 50, 
                       t = 125))

DCT_trends
```

```{r}
DCT_linear <- ggplotly(ggplot(df %>% filter (Season_num < 3)) + 
                         stat_smooth(aes(x = period, y = dct_values, color = Show_Name), 
                                     geom = "line", se = F, method = "lm", alpha = 0.6) + 
                         scale_colour_hue(h = c(180, 270)) + 
                         stat_smooth(data = filter(df, Network == "BRVO", Season_num < 3), 
                                     aes(x = period, y = dct_values, linetype = Network), 
                                     geom = "line", se = F, method = "lm", 
                                     color = "#7a0177", size = 1.3) + 
                         stat_smooth(data = filter(df, Network == "ENT", Season_num < 3), 
                                     aes(x = period, y = dct_values, linetype = Network), 
                                     geom = "line", se = F, method = "lm", 
                                     color = "#ae017e", size = 1.3) + 
                         stat_smooth(data = filter(df, Network == "SYFY", Season_num < 3), 
                                     aes(x = period, y = dct_values, linetype = Network), 
                                     geom = "line", se = F, method = "lm", 
                                     color = "#dd3497", size = 1.3) + 
                         stat_smooth(data = filter(df, Network == "USA", Season_num < 3), 
                                     aes(x = period, y = dct_values, linetype = Network), 
                                     geom = "line", se = F, method = "lm", 
                                     color = "#f768a1", size = 1.3) + 
                         stat_smooth(aes(x = period, y = dct_values), 
                                     geom = "line", se = F, method = "lm", 
                                     color = "black", linetype = "dashed", size = 1.4) + 
                         facet_wrap(~Season_num, nrow = 2) + my_theme) %>% 
  layout(title = "DCT Linear Trends for All Shows and Networks (C3)", 
         autosize = FALSE, width = 650, height = 800, 
         margin = list(l = 50, 
                       r = 50, 
                       b = 50, 
                       t = 125))

DCT_linear
```

# Growth

Read data
```{r}
df_growth <- read.csv("dct_C3_growth.csv")
```

## DCT Values Trends

```{r}
DCT_growth_trends <- ggplotly(ggplot(df_growth %>% filter(Season_num < 3)) + 
                                geom_line(aes(x = period, y = dct_values, 
                                              color = Show_Name), alpha = 0.6) + 
                                scale_colour_hue(h = c(180, 270)) + 
                                geom_line(data = df_growth %>% 
                                            filter(Season_num < 3, Network == "BRVO") %>% 
                                            group_by(Network, Season_num, period) %>% 
                                            summarise(avg = mean(dct_values)), 
                                          aes(x = period, y = avg, linetype = Network), 
                                          size = 1.2, color = "#7a0177") + 
                                geom_line(data = df_growth %>% 
                                            filter(Season_num < 3, Network == "ENT") %>% 
                                            group_by(Network, Season_num, period) %>% 
                                            summarise(avg = mean(dct_values)), 
                                          aes(x = period, y = avg, linetype = Network), 
                                          size = 1.2, color = "#ae017e") + 
                                geom_line(data = df_growth %>% 
                                            filter(Season_num < 3, Network == "SYFY") %>% 
                                            group_by(Network, Season_num, period) %>% 
                                            summarise(avg = mean(dct_values)), 
                                          aes(x = period, y = avg, linetype = Network), 
                                          size = 1.2, color = "#dd3497") + 
                                geom_line(data = df_growth %>% 
                                            filter(Season_num < 3, Network == "USA") %>% 
                                            group_by(Network, Season_num, period) %>% 
                                            summarise(avg = mean(dct_values)), 
                                          aes(x = period, y = avg, linetype = Network), 
                                          size = 1.2, color = "#f768a1") + 
                                geom_line(data = df_growth %>% 
                                            filter(Season_num < 3) %>% 
                                            group_by(Season_num, period) %>% 
                                            summarise(avg = mean(dct_values)), 
                                          aes(x = period, y = avg, color = Show_Name), 
                                          color = "black", linetype = "dashed",size = 1.3) + 
                                facet_wrap(~Season_num, nrow = 2) + my_theme) %>% 
  layout(title = "DCT Growth Trends for All Shows and Networks (C3)", 
         autosize = FALSE, width = 650, height = 800, 
         margin = list(l = 50, 
                       r = 50, 
                       b = 50, 
                       t = 125))

DCT_growth_trends
```

```{r}
DCT_growth_linear <- ggplotly(ggplot(df_growth  %>% filter (Season_num < 3)) + 
                                stat_smooth(aes(x = period, y = dct_values, color = Show_Name), 
                                            geom = "line", se = F, method = "lm", alpha = 0.6) + 
                                scale_colour_hue(h = c(180, 270)) + 
                                stat_smooth(data = filter(df_growth, Network == "BRVO", Season_num < 3), 
                                            aes(x = period, y = dct_values, linetype = Network), 
                                            geom = "line", se = F, method = "lm", 
                                            color = "#7a0177", size = 1.3) + 
                                stat_smooth(data = filter(df_growth, Network == "ENT", Season_num < 3), 
                                            aes(x = period, y = dct_values, linetype = Network), 
                                            geom = "line", se = F, method = "lm", 
                                            color = "#ae017e", size = 1.3) + 
                                stat_smooth(data = filter(df_growth, Network == "SYFY", Season_num < 3), 
                                            aes(x = period, y = dct_values, linetype = Network), 
                                            geom = "line", se = F, method = "lm", 
                                            color = "#dd3497", size = 1.3) + 
                                stat_smooth(data = filter(df_growth, Network == "USA", Season_num < 3), 
                                            aes(x = period, y = dct_values, linetype = Network), 
                                            geom = "line", se = F, method = "lm", 
                                            color = "#f768a1", size = 1.3) + 
                                stat_smooth(aes(x = period, y = dct_values), geom = "line", se = F, 
                                            method = "lm", color = "black", 
                                            linetype = "dashed", size = 1.4) + 
                                facet_wrap(~Season_num, nrow = 2) + my_theme) %>% 
  layout(title = "DCT Growth Linear Trends for All Shows and Networks (C3)", 
         autosize = FALSE, width = 650, height = 800,
         margin = list(l = 50, 
                       r = 50, 
                       b = 50, 
                       t = 125))

DCT_growth_linear
```

