---
title: "CENT S1 K-Means Clustering on Raw & Growth Together"
output:
  html_notebook: default
  html_document: default
---

```{r}
##################################################################################
# inputs: dct_C3_raw_growth.csv, dct_spread_C3_raw_growth.csv, 
#         dct_LS_raw_growth.csv, dct_spread_LS_raw_growth.csv 
#
# purpose: K-Means clustering for CENT S1 using raw and growth together,
#          for C3 and LS
##################################################################################
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r}
library(dplyr)
library(broom)
library(ggplot2)
library(plotly)
library(factoextra)
library(dtwclust)
library(fpc)
```

# S1 Curve Clustering on C3 Raw & Growth Appended

Using examples from https://cran.r-project.org/web/packages/broom/vignettes/kmeans.html.

```{r}
dct_df <- read.csv("dct_C3_raw_growth.csv") %>% select(-X)
dct_spread <- read.csv("dct_spread_C3_raw_growth.csv") %>% select(-X)
```

```{r}
cluster_s1_C3 <- dct_spread %>% 
  filter(Season_num == 1) %>%
  ungroup() %>%
  select(-Network, -Season_num, -Show_Name)
```

## General K-Means Clustering

```{r}
set.seed(12)
kclusts_s1 <- data.frame(k = 1:5) %>% 
  group_by(k) %>% 
  do(kclust = kmeans(cluster_s1_C3, centers = .$k, nstart = 20))

assignments_s1_C3 <- kclusts_s1 %>% group_by(k) %>% do(augment(.$kclust[[1]], cluster_s1_C3))
```

### Optimal Number of Clusters

```{r}
fviz_nbclust(cluster_s1_C3, 
             kmeans, 
             method = "wss",
             k.max = 5)
```

```{r}
fviz_nbclust(cluster_s1_C3, 
             kmeans, 
             method = "silhouette",
             k.max = 5)
```

```{r}
fviz_nbclust(cluster_s1_C3, 
             kmeans, 
             method = "gap_stat",
             k.max = 5)
```

```{r}
fviz_nbclust(cluster_s1_C3, 
             cluster::pam, 
             method = "gap_stat",
             k.max = 5)
```

```{r}
fviz_nbclust(cluster_s1_C3, 
             hcut, 
             hc_method = "single",
             hc_metric = "euclidean",
             method = "gap_stat",
             k.max = 5)
```

```{r}
fviz_nbclust(cluster_s1_C3, 
             hcut, 
             hc_method = "single",
             hc_metric = "pearson",
             method = "silhouette",
             k.max = 5,
             nboot = 500)
```

### 4 Clusters (K-Means)

```{r}
clusters4_s1_spread_C3 <- assignments_s1_C3 %>% 
  filter(k == 4) %>% 
  ungroup() %>% 
  select(.cluster) %>% 
  rename(cluster_kmeans_4 = .cluster) %>% 
  bind_cols(filter(dct_spread, Season_num == 1)) 

clusters4_s1_C3 <- merge(clusters4_s1_spread_C3[, c("cluster_kmeans_4", "Show_Name")], 
                      dct_df, by = "Show_Name")

clusters4_s1_C3_plot <- clusters4_s1_C3 %>% 
  filter(Season_num == 1) %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster_kmeans_4, nrow = 4) + 
  theme(axis.title.x = element_blank(), 
        axis.title.y = element_blank())

ggplotly(clusters4_s1_C3_plot) %>% 
  layout(title = "Season 1 with 4 K-Means Clusters (C3 Raw & Growth)", 
         margin = list(t = 150))
```

### 5 Clusters (K-Means)

```{r}
clusters5_s1_spread_C3 <- assignments_s1_C3 %>% 
  filter(k == 5) %>% 
  ungroup() %>% 
  select(.cluster) %>% 
  rename(cluster_kmeans_5 = .cluster) %>% 
  bind_cols(filter(dct_spread, Season_num == 1)) 

clusters5_s1_C3 <- merge(clusters5_s1_spread_C3[, c("cluster_kmeans_5", "Show_Name")], 
                      dct_df, by = "Show_Name")

write.csv(clusters5_s1_C3, "kmeans_raw_growth_C3_s1_5cl.csv")
```

```{r}
clusters5_s1_C3_plot <- clusters5_s1_C3 %>% 
  filter(Season_num == 1) %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster_kmeans_5, nrow = 5) + 
  theme(axis.title.x = element_blank(), 
        axis.title.y = element_blank())

ggplotly(clusters5_s1_C3_plot) %>% 
  layout(title = "Season 1 with 5 K-Means Clusters (C3 Raw & Growth)", 
         margin = list(t = 150))
```



# S1 Curve Clustering on LS Raw & Growth Appended

Using examples from https://cran.r-project.org/web/packages/broom/vignettes/kmeans.html.

```{r}
dct_df <- read.csv("dct_LS_raw_growth.csv") %>% select(-X)
dct_spread <- read.csv("dct_spread_LS_raw_growth.csv") %>% select(-X)
```

```{r}
cluster_s1_LS <- dct_spread %>% 
  filter(Season_num == 1) %>%
  ungroup() %>%
  select(-Network, -Season_num, -Show_Name)
```

## General K-Means Clustering

```{r}
set.seed(12)
kclusts_s1 <- data.frame(k = 1:5) %>% 
  group_by(k) %>% 
  do(kclust = kmeans(cluster_s1_LS, centers = .$k, nstart = 20))

assignments_s1_LS <- kclusts_s1 %>% group_by(k) %>% do(augment(.$kclust[[1]], cluster_s1_LS))
```

### Optimal Number of Clusters

```{r}
fviz_nbclust(cluster_s1_LS, 
             kmeans, 
             method = "wss",
             k.max = 5)
```

```{r}
fviz_nbclust(cluster_s1_LS, 
             kmeans, 
             method = "silhouette",
             k.max = 5)
```

```{r}
fviz_nbclust(cluster_s1_LS, 
             kmeans, 
             method = "gap_stat",
             k.max = 5)
```

```{r}
fviz_nbclust(cluster_s1_LS, 
             cluster::pam, 
             method = "gap_stat",
             k.max = 5)
```

```{r}
fviz_nbclust(cluster_s1_LS, 
             hcut, 
             hc_method = "single",
             hc_metric = "euclidean",
             method = "gap_stat",
             k.max = 5)
```

```{r}
fviz_nbclust(cluster_s1_LS, 
             hcut, 
             hc_method = "single",
             hc_metric = "pearson",
             method = "silhouette",
             k.max = 5,
             nboot = 500)
```

### 5 Clusters (K-Means)

```{r}
clusters5_s1_spread_LS <- assignments_s1_LS %>% 
  filter(k == 5) %>% 
  ungroup() %>% 
  select(.cluster) %>% 
  rename(cluster_kmeans_5 = .cluster) %>% 
  bind_cols(filter(dct_spread, Season_num == 1)) 

clusters5_s1_LS <- merge(clusters5_s1_spread_LS[, c("cluster_kmeans_5", "Show_Name")], 
                      dct_df, by = "Show_Name")

write.csv(clusters5_s1_LS, "kmeans_raw_growth_LS_s1_5cl.csv")
```

```{r}
clusters5_s1_LS_plot <- clusters5_s1_LS %>% 
  filter(Season_num == 1) %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster_kmeans_5, nrow = 5) + 
  theme(axis.title.x = element_blank(), 
        axis.title.y = element_blank())

ggplotly(clusters5_s1_LS_plot) %>% 
  layout(title = "Season 1 with 5 K-Means Clusters (LS Raw & Growth)", 
         margin = list(t = 150))
```

# Diagnostics
 
```{r}
# create distance matrices for clusters
kmeans_s1_4cl_d_C3 <- dist(clusters4_s1_spread_C3[, 5:204])
kmeans_s1_5cl_d_C3 <- dist(clusters5_s1_spread_C3[, 5:204])
kmeans_s1_5cl_d_LS <- dist(clusters5_s1_spread_LS[, 5:204])

# diagnostics
diagnostics_kmeans_raw_growth_C3_s1_4cl <- cluster.stats(kmeans_s1_4cl_d_C3, as.numeric(clusters4_s1_spread_C3$cluster_kmeans_4))
diagnostics_kmeans_raw_growth_C3_s1_5cl <- cluster.stats(kmeans_s1_5cl_d_C3, as.numeric(clusters5_s1_spread_C3$cluster_kmeans_5))
diagnostics_kmeans_raw_growth_LS_s1_5cl <- cluster.stats(kmeans_s1_5cl_d_LS, as.numeric(clusters5_s1_spread_LS$cluster_kmeans_5))

# gather diagnostic names and list all diagnostics objects
d_names <- ls()[grep("diagnostics", ls())]
d_list <- mget(ls()[grep("diagnostics", ls())])

# generate df with statsitics of interest for comparison
diagnostic_df <- as.data.frame(NA)

for (n in 1:length(d_names)){
  diagnostic_df[n, 1] <- paste(d_names[n])
  diagnostic_df[n, 2] <- d_list[[n]]["average.between"]
  diagnostic_df[n, 3] <- d_list[[n]]["average.within"]
  diagnostic_df[n, 4] <- d_list[[n]]["wb.ratio"]
  diagnostic_df[n, 5] <- d_list[[n]]["widestgap"]
  diagnostic_df[n, 6] <- d_list[[n]]["dunn2"]
  diagnostic_df[n, 7] <- d_list[[n]]["avg.silwidth"]
  diagnostic_df[n, 8] <- d_list[[n]]["within.cluster.ss"]
  diagnostic_df[n, 9] <- d_list[[n]]["cluster.number"]
}

# add information for decision making
colnames(diagnostic_df)[1] <- "name"

diagnostic_df$name <- sub("diagnostics_", "", diagnostic_df$name)

diagnostic_df$algorithm <- ifelse(grepl("kmeans", diagnostic_df$name) == 1, "kmeans", 
                                  ifelse(grepl("kshape", diagnostic_df$name) == 1, "kshape", 
                                         ifelse(grepl("PCA", diagnostic_df$name) == 1, "PCA", 
                                                ifelse(grepl("tadpole", diagnostic_df$name) == 1, "TADpole", 
                                                       ifelse(grepl("dtw", diagnostic_df$name) == 1, "DTW", 0)))))

diagnostic_df$season <- ifelse(grepl("s1", diagnostic_df$name) == 1, "s1", 
                               ifelse(grepl("s2", diagnostic_df$name) == 1, "s2",
                                      ifelse(grepl("sep", diagnostic_df$name) == 1, "sep",
                                             ifelse(grepl("cont", diagnostic_df$name) == 1, "cont", 0))))

diagnostic_df$stream <- ifelse(grepl("C3_LS", diagnostic_df$name) == 1, "C3+LS",
                                             ifelse(grepl("LS", diagnostic_df$name) == 1, "LS",
                                                    ifelse(grepl("C3", diagnostic_df$name) == 1, "C3", 0)))

diagnostic_df$data <- ifelse(grepl("raw_diff", diagnostic_df$name) == 1, "raw diff",
                             ifelse(grepl("raw_avg", diagnostic_df$name) == 1, "raw avg",
                                    ifelse(grepl("growth_diff", diagnostic_df$name) == 1, "growth diff",
                                           ifelse(grepl("growth_avg", diagnostic_df$name) == 1, "growth avg", 
                                                  ifelse(grepl("raw_growth", diagnostic_df$name) == 1, "raw+growth",
                                                         ifelse(grepl("growth", diagnostic_df$name) == 1, "growth",
                                                                ifelse(grepl("raw", diagnostic_df$name) == 1, "raw",0)))))))
```

```{r}
# write table
write.csv(diagnostic_df, "diagnostics_kmeans_raw_growth.csv")
```