---
title: "CENT S1-S2 PCA Clustering on C3 & LS Impressions"
output:
  html_notebook: default
  html_document: default
---

```{r}
##################################################################################
# inputs: dct_C3_LS_raw.csv, dct_spread_C3_LS_raw.csv, 
#         dct_C3_LS_diff.csv, dct_spread_C3_LS_diff.csv, 
#         dct_C3_LS_avg.csv, dct_spread_C3_LS_avg.csv 
#
# purpose: PCA clustering for C3 & LS appended, differences, and averages
##################################################################################
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
library(plotly)
library(fpc)
```

# C3 & LS Appended

Read and prepare data
```{r}
dct_spread <- read.csv("dct_spread_C3_LS_raw.csv")
dct_df <- read.csv("dct_C3_LS_raw.csv")

pca_s1 <- dct_spread %>% 
  filter(Season_num == 1) %>%
  ungroup() %>%
  select(-X, -Network, -Season_num, -Show_Name)
```

PCA
```{r}
pca_s1 <- prcomp(pca_s1)

summary(pca_s1)
```

Assign clusters based on PCA contribution
```{r}
pca_s1_df <- as.data.frame(pca_s1$x)
pca_s1_df$Show_name <- dct_spread[dct_spread$Season_num == 1,]$Show_Name

cluster_assign_s1<- pca_s1_df[,c(51, 1, 2, 3, 4)]
cluster_assign_s1$cluster <- max.col(cluster_assign_s1[, c(2, 3, 4, 5)], ties.method = "first")

df_pcaclusters_s1 <- dct_spread %>% filter(Season_num == 1) %>% 
  select(-X, -Season_num)
df_pcaclusters_s1$cluster <- cluster_assign_s1$cluster
df_pcaclusters_s1 <- df_pcaclusters_s1[,c(1, 2, 203, 3:202)]

pca_s1_long <- gather(df_pcaclusters_s1, key = period, value = dct_values, X1:X200)
pca_s1_long$period <- as.numeric(sub("X", "", pca_s1_long$period))

pca_s1_plot <- pca_s1_long %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster, nrow = 4)

ggplotly(pca_s1_plot) %>% 
  layout(title = "Season 1 with 4 PCA Clusters (C3 & LS)", 
         margin = list(t = 150))
```


-------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------


# C3-LS Differences

```{r}
dct_spread <- read.csv("dct_spread_C3_LS_diff.csv") %>% select(-X)
dct_df <- read.csv("dct_C3_LS_diff.csv") %>% select(-X)

pca_diff <- dct_spread %>% 
  filter(Season_num == 2) %>%
  ungroup() %>%
  select(-Network, -Season_num, -Show_Name)
```

PCA
```{r}
pca_diff <- prcomp(pca_diff)

summary(pca_diff)
```

Assign clusters based on PCA contribution
```{r}
pca_diff_df <- as.data.frame(pca_diff$x)
pca_diff_df$Show_name <- dct_spread[dct_spread$Season_num == 1,]$Show_Name

cluster_assign_diff <- pca_diff_df[,c(51, 1, 2, 3)]
cluster_assign_diff$cluster <- max.col(cluster_assign_diff[, c(2, 3, 4)], ties.method = "first")

df_pcaclusters_diff <- dct_spread %>% filter(Season_num == 1) %>% 
  select(-Season_num)
df_pcaclusters_diff$cluster <- cluster_assign_diff$cluster
df_pcaclusters_diff <- df_pcaclusters_diff[,c(1, 2, 103, 3:102)]

pca_diff_long <- gather(df_pcaclusters_diff, key = period, value = dct_values ,X1:X100)
pca_diff_long$period <- as.numeric(sub("X", "", pca_diff_long$period))

pca_diff_plot <- pca_diff_long %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster, nrow = 3)

ggplotly(pca_diff_plot) %>% 
  layout(title = "Season 1 with 3 PCA Clusters (C3-LS Differences)", 
         margin = list(t = 150))
```


-------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------


# C3 & LS Averages

```{r}
dct_spread <- read.csv("dct_spread_C3_LS_avg.csv") %>% select(-X)
dct_df <- read.csv("dct_C3_LS_avg.csv") %>% select(-X)

pca_avg <- dct_spread %>% 
  filter(Season_num == 2) %>%
  ungroup() %>%
  select(-Network, -Season_num, -Show_Name)
```

PCA
```{r}
pca_avg <- prcomp(pca_avg)

summary(pca_avg)
```

Assign clusters based on PCA contribution
```{r}
pca_avg_df <- as.data.frame(pca_avg$x)
pca_avg_df$Show_name <- dct_spread[dct_spread$Season_num == 1,]$Show_Name

cluster_assign_avg <- pca_avg_df[,c(51, 1, 2, 3)]
cluster_assign_avg$cluster <- max.col(cluster_assign_avg[, c(2, 3, 4)], ties.method = "first")

df_pcaclusters_avg <- dct_spread %>% filter(Season_num == 1) %>% 
  select(-Season_num)
df_pcaclusters_avg$cluster <- cluster_assign_avg$cluster
df_pcaclusters_avg <- df_pcaclusters_avg[,c(1, 2, 103, 3:102)]

pca_avg_long <- gather(df_pcaclusters_avg, key = period, value = dct_values ,X1:X100)
pca_avg_long$period <- as.numeric(sub("X", "", pca_avg_long$period))

pca_avg_plot <- pca_avg_long %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster, nrow = 3)

ggplotly(pca_avg_plot) %>% 
  layout(title = "Season 1 with 3 PCA Clusters (C3 & LS Averages)", 
         margin = list(t = 150))
```

# Diagnostics

```{r}
# create distance matrices for clusters
pca_s1_4cl_d <- dist(df_pcaclusters_s1[, 4:203])
pca_diff_3cl_d <- dist(df_pcaclusters_diff[, 4:103])
pca_avg_3cl_d <- dist(df_pcaclusters_avg[, 4:103])

# diagnostics
diagnostics_pca_C3_LS_raw_s1_4cl <- cluster.stats(pca_s1_4cl_d, as.numeric(df_pcaclusters_s1$cluster))
diagnostics_pca_C3_LS_raw_diff_s1_3cl <- cluster.stats(pca_diff_3cl_d, as.numeric(df_pcaclusters_diff$cluster))
diagnostics_pca_C3_LS_raw_avg_s1_3cl <- cluster.stats(pca_avg_3cl_d, as.numeric(df_pcaclusters_avg$cluster))

# gather diagnostic names and list all diagnostics objects
d_names <- ls()[grep("diagnostics", ls())]
d_list <- mget(ls()[grep("diagnostics", ls())])

# generate df with statsitics of interest for comparison
diagnostic_df <- as.data.frame(NA)

for (n in 1:length(d_names)){
  diagnostic_df[n, 1] <- paste(d_names[n])
  diagnostic_df[n, 2] <- d_list[[n]]["average.between"]
  diagnostic_df[n, 3] <- d_list[[n]]["average.within"]
  diagnostic_df[n, 4] <- d_list[[n]]["wb.ratio"]
  diagnostic_df[n, 5] <- d_list[[n]]["widestgap"]
  diagnostic_df[n, 6] <- d_list[[n]]["dunn2"]
  diagnostic_df[n, 7] <- d_list[[n]]["avg.silwidth"]
  diagnostic_df[n, 8] <- d_list[[n]]["within.cluster.ss"]
  diagnostic_df[n, 9] <- d_list[[n]]["cluster.number"]
}

# add information for decision making
colnames(diagnostic_df)[1] <- "name"

diagnostic_df$name <- sub("diagnostics_", "", diagnostic_df$name)

diagnostic_df$algorithm <- ifelse(grepl("kmeans", diagnostic_df$name) == 1, "kmeans", 
                                  ifelse(grepl("kshape", diagnostic_df$name) == 1, "kshape", 
                                         ifelse(grepl("pca", diagnostic_df$name) == 1, "PCA", 
                                                ifelse(grepl("tadpole", diagnostic_df$name) == 1, "TADpole", 
                                                       ifelse(grepl("dtw", diagnostic_df$name) == 1, "DTW", 0)))))

diagnostic_df$season <- ifelse(grepl("s1", diagnostic_df$name) == 1, "s1", 
                               ifelse(grepl("s2", diagnostic_df$name) == 1, "s2",
                                      ifelse(grepl("sep", diagnostic_df$name) == 1, "sep",
                                             ifelse(grepl("cont", diagnostic_df$name) == 1, "cont", 0))))

diagnostic_df$stream <- ifelse(grepl("C3_LS", diagnostic_df$name) == 1, "C3+LS",
                                             ifelse(grepl("LS", diagnostic_df$name) == 1, "LS",
                                                    ifelse(grepl("C3", diagnostic_df$name) == 1, "C3", 0)))

diagnostic_df$data <- ifelse(grepl("raw_diff", diagnostic_df$name) == 1, "raw diff",
                             ifelse(grepl("raw_avg", diagnostic_df$name) == 1, "raw avg",
                                    ifelse(grepl("growth_diff", diagnostic_df$name) == 1, "growth diff",
                                           ifelse(grepl("growth_avg", diagnostic_df$name) == 1, "growth avg", 
                                                  ifelse(grepl("raw_growth", diagnostic_df$name) == 1, "raw+growth",
                                                         ifelse(grepl("growth", diagnostic_df$name) == 1, "growth",
                                                                ifelse(grepl("raw", diagnostic_df$name) == 1, "raw",0)))))))
```

```{r}
# write table
write.csv(diagnostic_df, "diagnostics_pca_C3_LS_raw.csv")
```
