---
title: "CENT S1-S2 PCA Clustering on Raw & Growth"
output:
  html_notebook: default
  html_document: default
---

```{r}
##################################################################################
# inputs: dct_C3_raw_growth.csv, dct_spread_C3_raw_growth.csv, 
#         dct_LS_raw_growth.csv, dct_spread_LS_raw_growth.csv
#
# purpose: PCA clustering for C3 & LS growth appended, differences, and averages
##################################################################################
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
library(plotly)
library(fpc)
```

# C3 Raw & Growth

Read and prepare data
```{r}
dct_spread <- read.csv("dct_spread_C3_raw_growth.csv") %>% select(-X)
dct_df <- read.csv("dct_C3_raw_growth.csv") %>% select(-X)

pca_C3 <- dct_spread %>% 
  filter(Season_num == 1) %>%
  ungroup() %>%
  select(-Network, -Season_num, -Show_Name)
```

PCA
```{r}
#run PCA on data
pca_C3 <- prcomp(pca_C3)

summary(pca_C3)
```

Assign clusters based on PCA contribution
```{r}

#PCA rotations per PC, per show name
pca_C3_df <- as.data.frame(pca_C3$x)
pca_C3_df$Show_name <- dct_spread[dct_spread$Season_num == 1,]$Show_Name

#First three components. Cluster assigned on highest rotation on PC
cluster_assign_C3<- pca_C3_df[,c(49, 1, 2, 3, 4)]
cluster_assign_C3$cluster <- max.col(cluster_assign_C3[, c(2, 3, 4, 5)], ties.method = "first")

#merge with dct data
df_pcaclusters_C3 <- dct_spread %>% filter(Season_num == 1) %>% 
  select(-Season_num)
df_pcaclusters_C3$cluster <- cluster_assign_C3$cluster
df_pcaclusters_C3 <- df_pcaclusters_C3[,c(1, 2, 203, 3:202)]

pca_C3_long <- gather(df_pcaclusters_C3, key = period, value = dct_values, X1:X200)
pca_C3_long$period <- as.numeric(sub("X", "", pca_C3_long$period))

#Plot
pca_C3_plot <- pca_C3_long %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster, nrow = 4)

ggplotly(pca_C3_plot) %>% 
  layout(title = "Season 1 with 4 PCA Clusters (C3 Raw & Growth)", 
         margin = list(t = 150))
```


-------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------

```{r}
#Code is the same for different data
```

# LS Raw & Growth

Read and prepare data
```{r}
dct_spread <- read.csv("dct_spread_LS_raw_growth.csv") %>% select(-X)
dct_df <- read.csv("dct_LS_raw_growth.csv") %>% select(-X)

pca_LS <- dct_spread %>% 
  filter(Season_num == 1) %>%
  ungroup() %>%
  select(-Network, -Season_num, -Show_Name)
```

PCA
```{r}
pca_LS <- prcomp(pca_LS)

summary(pca_LS)
```

Assign clusters based on PCA contribution
```{r}
pca_LS_df <- as.data.frame(pca_LS$x)
pca_LS_df$Show_name <- dct_spread[dct_spread$Season_num == 1,]$Show_Name

cluster_assign_LS<- pca_LS_df[,c(49, 1, 2, 3, 4)]
cluster_assign_LS$cluster <- max.col(cluster_assign_LS[, c(2, 3, 4, 5)], ties.method = "first")

df_pcaclusters_LS <- dct_spread %>% filter(Season_num == 1) %>% 
  select(-Season_num)
df_pcaclusters_LS$cluster <- cluster_assign_LS$cluster
df_pcaclusters_LS <- df_pcaclusters_LS[,c(1, 2, 203, 3:202)]

pca_LS_long <- gather(df_pcaclusters_LS, key = period, value = dct_values, X1:X200)
pca_LS_long$period <- as.numeric(sub("X", "", pca_LS_long$period))

pca_LS_plot <- pca_LS_long %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster, nrow = 4)

ggplotly(pca_LS_plot) %>% 
  layout(title = "Season 1 with 4 PCA Clusters (LS Raw & Growth)", 
         margin = list(t = 150))
```

# Diagnostics

```{r}
# create distance matrices for clusters
pca_C3_4cl_d <- dist(df_pcaclusters_C3[, 4:203])
pca_LS_4cl_d <- dist(df_pcaclusters_LS[, 4:203])

# diagnostics
diagnostics_pca_raw_growth_C3_s1_4cl <- cluster.stats(pca_C3_4cl_d, as.numeric(df_pcaclusters_C3$cluster))
diagnostics_pca_raw_growth_LS_s1_4cl <- cluster.stats(pca_LS_4cl_d, as.numeric(df_pcaclusters_LS$cluster))

# gather diagnostic names and list all diagnostics objects
d_names <- ls()[grep("diagnostics", ls())]
d_list <- mget(ls()[grep("diagnostics", ls())])

# generate df with statsitics of interest for comparison
diagnostic_df <- as.data.frame(NA)

for (n in 1:length(d_names)){
  diagnostic_df[n, 1] <- paste(d_names[n])
  diagnostic_df[n, 2] <- d_list[[n]]["average.between"]
  diagnostic_df[n, 3] <- d_list[[n]]["average.within"]
  diagnostic_df[n, 4] <- d_list[[n]]["wb.ratio"]
  diagnostic_df[n, 5] <- d_list[[n]]["widestgap"]
  diagnostic_df[n, 6] <- d_list[[n]]["dunn2"]
  diagnostic_df[n, 7] <- d_list[[n]]["avg.silwidth"]
  diagnostic_df[n, 8] <- d_list[[n]]["within.cluster.ss"]
  diagnostic_df[n, 9] <- d_list[[n]]["cluster.number"]
}

# add information for decision making
colnames(diagnostic_df)[1] <- "name"

diagnostic_df$name <- sub("diagnostics_", "", diagnostic_df$name)

diagnostic_df$algorithm <- ifelse(grepl("kmeans", diagnostic_df$name) == 1, "kmeans", 
                                  ifelse(grepl("kshape", diagnostic_df$name) == 1, "kshape", 
                                         ifelse(grepl("pca", diagnostic_df$name) == 1, "PCA", 
                                                ifelse(grepl("tadpole", diagnostic_df$name) == 1, "TADpole", 
                                                       ifelse(grepl("dtw", diagnostic_df$name) == 1, "DTW", 0)))))

diagnostic_df$season <- ifelse(grepl("s1", diagnostic_df$name) == 1, "s1", 
                               ifelse(grepl("s2", diagnostic_df$name) == 1, "s2",
                                      ifelse(grepl("sep", diagnostic_df$name) == 1, "sep",
                                             ifelse(grepl("cont", diagnostic_df$name) == 1, "cont", 0))))

diagnostic_df$stream <- ifelse(grepl("C3_LS", diagnostic_df$name) == 1, "C3+LS",
                                             ifelse(grepl("LS", diagnostic_df$name) == 1, "LS",
                                                    ifelse(grepl("C3", diagnostic_df$name) == 1, "C3", 0)))

diagnostic_df$data <- ifelse(grepl("raw_diff", diagnostic_df$name) == 1, "raw diff",
                             ifelse(grepl("raw_avg", diagnostic_df$name) == 1, "raw avg",
                                    ifelse(grepl("growth_diff", diagnostic_df$name) == 1, "growth diff",
                                           ifelse(grepl("growth_avg", diagnostic_df$name) == 1, "growth avg", 
                                                  ifelse(grepl("raw_growth", diagnostic_df$name) == 1, "raw+growth",
                                                         ifelse(grepl("growth", diagnostic_df$name) == 1, "growth",
                                                                ifelse(grepl("raw", diagnostic_df$name) == 1, "raw",0)))))))
```

```{r}
# write table
write.csv(diagnostic_df, "diagnostics_pca_raw_growth.csv")
```
