---
title: "CENT S1-S2 PCA Clustering on C3 Impressions"
output:
  html_notebook: default
  html_document: default
---

```{r}
##################################################################################
# inputs: dct_C3_raw.csv, dct_spread_C3_raw.csv, dct_spread_C3_raw_cont.csv, 
#
# purpose: PCA clustering (3 clusters (Cumulative proportion of variance = 1.0 at
#          3 Principal components for all PCAs, but for non-contiuous s1-s2,
#          4 clusters for the latter) for S1, S2, and S1 & S2 normalized together)
##################################################################################
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
library(plotly)
library(fpc)
```

# PCA S1

Read and prepare data
```{r}
dct_spread <- read.csv("dct_spread_C3_raw.csv")
dct_df <- read.csv("dct_C3_raw.csv")

pca_s1 <- dct_spread %>% 
  filter(Season_num == 1) %>%
  ungroup() %>%
  select(-X, -Network, -Season_num, -Show_Name)
```

PCA
```{r}
pca_s1 <- prcomp(pca_s1)

summary(pca_s1)
```

Assign clusters based on PCA contribution
```{r}
pca_s1_df <- as.data.frame(pca_s1$x)
pca_s1_df$Show_name <- dct_spread[dct_spread$Season_num == 1,]$Show_Name

cluster_assign_s1<- pca_s1_df[,c(51, 1, 2, 3)]
cluster_assign_s1$cluster <- max.col(cluster_assign_s1[, c(2, 3, 4)], ties.method = "first")

df_pcaclusters_s1 <- dct_spread %>% filter(Season_num == 1) %>% 
  select(-X, -Season_num)
df_pcaclusters_s1$cluster <- cluster_assign_s1$cluster
df_pcaclusters_s1 <- df_pcaclusters_s1[,c(1, 2, 103, 3:102)]

pca_s1_long <- gather(df_pcaclusters_s1, key = period, value = dct_values ,X1:X100)
pca_s1_long$period <- as.numeric(sub("X", "", pca_s1_long$period))

pca_s1_plot <- pca_s1_long %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster, nrow = 3)

ggplotly(pca_s1_plot) %>% 
  layout(title = "Season 1 with 3 PCA Clusters (C3)", 
         margin = list(t = 150))
```

### Shows in Each Cluster

```{r}
pca_s1_clusters <- list(as.character(unique(df_pcaclusters_s1[df_pcaclusters_s1$cluster == 1,]$Show_Name)),
                        as.character(unique(df_pcaclusters_s1[df_pcaclusters_s1$cluster == 2,]$Show_Name)),
                        as.character(unique(df_pcaclusters_s1[df_pcaclusters_s1$cluster == 3,]$Show_Name)))
pca_s1_clusters 
```

```{r}
# PLOT FOR S1 CLUSTERS & S2 TRENDS
s2_spread <- dct_spread %>% 
  filter(Season_num == 2) %>%
  ungroup() %>%
  select(-X, -Network, -Season_num)

s2_spread_newcols <- c(paste("X", 101:200, sep = ""))
colnames(s2_spread)[2:ncol(s2_spread)] <- c(s2_spread_newcols)

s1_pcaclusters_s2_trends <- bind_cols(df_pcaclusters_s1, 
                                      s2_spread[, 2:ncol(s2_spread)])

s1_pcaclusters_s2_trends <- merge(s1_pcaclusters_s2_trends[, c("cluster", "Show_Name")], 
                                  dct_df, by = "Show_Name")

dct_s1_pcaclusters_s2_trends <- s1_pcaclusters_s2_trends %>% 
  filter(Season_num == 1 | Season_num == 2) %>% 
  group_by(Network, Show_Name) %>% 
  mutate(period = row_number())

s1_pcaclusters_s2_trends_plot <- dct_s1_pcaclusters_s2_trends %>%
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster, nrow = 3) + 
  theme(axis.title.x = element_blank(), 
        axis.title.y = element_blank())

ggplotly(s1_pcaclusters_s2_trends_plot) %>% 
  layout(title = "Season 1 with 3 PCA Clusters & Season 2 Trends (C3)", 
         margin = list(t = 150))
```


-------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------


# PCA S2

```{r}
pca_s2 <- dct_spread %>% 
  filter(Season_num == 2) %>%
  ungroup() %>%
  select(-X, -Network, -Season_num, -Show_Name)
```

PCA
```{r}
pca_s2 <- prcomp(pca_s2)

summary(pca_s2)
```

Assign clusters based on PCA contribution
```{r}
pca_s2_df <- as.data.frame(pca_s2$x)
pca_s2_df$Show_name <- dct_spread[dct_spread$Season_num == 2,]$Show_Name

cluster_assign_s2<- pca_s2_df[,c(51, 1, 2, 3)]
cluster_assign_s2$cluster <- max.col(cluster_assign_s2[, c(2, 3, 4)], ties.method = "first")

df_pcaclusters_s2 <- dct_spread %>% filter(Season_num == 2) %>% 
  select(-X, -Season_num)
df_pcaclusters_s2$cluster <- cluster_assign_s2$cluster
df_pcaclusters_s2 <- df_pcaclusters_s2[,c(1, 2, 103, 3:102)]

pca_s2_long <- gather(df_pcaclusters_s2, key = period, value = dct_values ,X1:X100)
pca_s2_long$period <- as.numeric(sub("X", "", pca_s2_long$period))

pca_s2_plot <- pca_s2_long %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster, nrow = 3)

ggplotly(pca_s2_plot) %>% 
  layout(title = "Season 2 with 3 PCA Clusters (C3)", 
         margin = list(t = 150))
```

### Shows in Each Cluster

```{r}
pca_s2_clusters <- list(as.character(unique(df_pcaclusters_s2[df_pcaclusters_s2$cluster == 1,]$Show_Name)),
                        as.character(unique(df_pcaclusters_s2[df_pcaclusters_s2$cluster == 2,]$Show_Name)),
                        as.character(unique(df_pcaclusters_s2[df_pcaclusters_s2$cluster == 3,]$Show_Name)))
pca_s2_clusters 
```


-------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------


# PCA S1-S2 Continuous

```{r}
dct_spread_cont <- read.csv("dct_spread_C3_raw_cont.csv")
pca_cont <- dct_spread_cont %>%
  select(-X, -Network, -Show_Name)
```

PCA
```{r}
pca_cont <- prcomp(pca_cont)

summary(pca_cont)
```

Assign clusters based on PCA contribution
```{r}
pca_cont_df <- as.data.frame(pca_cont$x)
pca_cont_df$Show_name <- dct_spread_cont$Show_Name

cluster_assign_cont<- pca_cont_df[,c(51, 1, 2, 3)]
cluster_assign_cont$cluster <- max.col(cluster_assign_cont[, c(2, 3, 4)], ties.method = "first")

df_pcaclusters_cont <- dct_spread_cont %>% select(-X)
df_pcaclusters_cont$cluster <- cluster_assign_cont$cluster
df_pcaclusters_cont <- df_pcaclusters_cont[,c(1, 2, 103, 3:102)]

pca_cont_long <- gather(df_pcaclusters_cont, key = period, value = dct_values ,X1:X100)
pca_cont_long$period <- as.numeric(sub("X", "", pca_cont_long$period))

pca_cont_plot <- pca_cont_long %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster, nrow = 3)

ggplotly(pca_cont_plot) %>% 
  layout(title = "S1-S2 (Continuous) with 3 PCA Clusters (C3)", 
         margin = list(t = 150))
```

### Shows in Each Cluster

```{r}
pca_cont_clusters <- list(as.character(unique(df_pcaclusters_cont[df_pcaclusters_cont$cluster == 1,]$Show_Name)),
                          as.character(unique(df_pcaclusters_cont[df_pcaclusters_cont$cluster == 2,]$Show_Name)),
                          as.character(unique(df_pcaclusters_cont[df_pcaclusters_cont$cluster == 3,]$Show_Name)))
pca_cont_clusters 
```


-------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------


# PCA S1-S2 Non-Continuous

```{r}
temp1 <- filter(dct_spread, Season_num == 1)
temp2 <- filter(dct_spread, Season_num == 2)
temp2_newcols <- c(paste("X", 101:200, sep = ""))
colnames(temp2)[5:ncol(temp2)] <- c(temp2_newcols)

dct_spread_s1_s2 <- bind_cols(temp1, temp2[, 5:ncol(temp2)])
rm(temp1, temp2, temp2_newcols)

pca_s1_s2 <- dct_spread_s1_s2 %>%
  select(-X, -Network, -Season_num, -Show_Name)
```

PCA
```{r}
pca_s1_s2 <- prcomp(pca_s1_s2)

summary(pca_s1_s2)
```

Assign clusters based on PCA contribution
```{r}
pca_s1_s2_df <- as.data.frame(pca_s1_s2$x)
pca_s1_s2_df$Show_name <- dct_spread[dct_spread$Season_num == 1, ]$Show_Name

cluster_assign_s1_s2<- pca_s1_s2_df[,c(49, 1, 2, 3, 4)]
cluster_assign_s1_s2$cluster <- max.col(cluster_assign_s1_s2[, c(2, 3, 4, 5)], ties.method = "first")

df_pcaclusters_s1_s2 <- dct_spread_s1_s2 %>% select(-X)
df_pcaclusters_s1_s2$cluster <- cluster_assign_s1_s2$cluster
df_pcaclusters_s1_s2 <- select(df_pcaclusters_s1_s2, -Season_num)
df_pcaclusters_s1_s2 <- df_pcaclusters_s1_s2[,c(1, 2, 203, 3:202)]

pca_s1_s2_long <- gather(df_pcaclusters_s1_s2, key = period, value = dct_values ,X1:X200)
pca_s1_s2_long$period <- as.numeric(sub("X", "", pca_s1_s2_long$period))

pca_s1_s2_plot <- pca_s1_s2_long %>% 
  ggplot(aes(x = period, y = dct_values, color = Show_Name)) + 
  geom_line() + 
  facet_wrap(~ cluster)

ggplotly(pca_s1_s2_plot) %>% 
  layout(title = "S1-S2 (Non-Continuous) with 4 PCA Clusters (C3)", 
         margin = list(t = 150))
```

### Shows in Each Cluster

```{r}
pca_s1_s2_clusters <- list(as.character(unique(df_pcaclusters_s1_s2[df_pcaclusters_s1_s2$cluster == 1,]$Show_Name)),
                           as.character(unique(df_pcaclusters_s1_s2[df_pcaclusters_s1_s2$cluster == 2,]$Show_Name)),
                           as.character(unique(df_pcaclusters_s1_s2[df_pcaclusters_s1_s2$cluster == 3,]$Show_Name)),
                           as.character(unique(df_pcaclusters_s1_s2[df_pcaclusters_s1_s2$cluster == 4,]$Show_Name)))
pca_s1_s2_clusters 
```

# Diagnostics

```{r}
# create distance matrices for clusters
pca_s1_3cl_d <- dist(df_pcaclusters_s1[, 4:103])
pca_s2_3cl_d <- dist(df_pcaclusters_s2[, 4:103])
pca_cont_3cl_d <- dist(df_pcaclusters_cont[, 4:103])
pca_sep_4cl_d <- dist(df_pcaclusters_s1_s2[, 4:203])

# diagnostics
diagnostics_pca_C3_raw_s1_3cl <- cluster.stats(pca_s1_3cl_d, as.numeric(df_pcaclusters_s1$cluster))
diagnostics_pca_C3_raw_s2_3cl <- cluster.stats(pca_s2_3cl_d, as.numeric(df_pcaclusters_s2$cluster))
diagnostics_pca_C3_raw_cont_3cl <- cluster.stats(pca_cont_3cl_d, as.numeric(df_pcaclusters_cont$cluster))
diagnostics_pca_C3_raw_sep_4cl <- cluster.stats(pca_sep_4cl_d, as.numeric(df_pcaclusters_s1_s2$cluster))

# gather diagnostic names and list all diagnostics objects
d_names <- ls()[grep("diagnostics", ls())]
d_list <- mget(ls()[grep("diagnostics", ls())])

# generate df with statsitics of interest for comparison
diagnostic_df <- as.data.frame(NA)

for (n in 1:length(d_names)){
  diagnostic_df[n, 1] <- paste(d_names[n])
  diagnostic_df[n, 2] <- d_list[[n]]["average.between"]
  diagnostic_df[n, 3] <- d_list[[n]]["average.within"]
  diagnostic_df[n, 4] <- d_list[[n]]["wb.ratio"]
  diagnostic_df[n, 5] <- d_list[[n]]["widestgap"]
  diagnostic_df[n, 6] <- d_list[[n]]["dunn2"]
  diagnostic_df[n, 7] <- d_list[[n]]["avg.silwidth"]
  diagnostic_df[n, 8] <- d_list[[n]]["within.cluster.ss"]
  diagnostic_df[n, 9] <- d_list[[n]]["cluster.number"]
}

# add information for decision making
colnames(diagnostic_df)[1] <- "name"

diagnostic_df$name <- sub("diagnostics_", "", diagnostic_df$name)

diagnostic_df$algorithm <- ifelse(grepl("kmeans", diagnostic_df$name) == 1, "kmeans", 
                                  ifelse(grepl("kshape", diagnostic_df$name) == 1, "kshape", 
                                         ifelse(grepl("pca", diagnostic_df$name) == 1, "PCA", 
                                                ifelse(grepl("tadpole", diagnostic_df$name) == 1, "TADpole", 
                                                       ifelse(grepl("dtw", diagnostic_df$name) == 1, "DTW", 0)))))

diagnostic_df$season <- ifelse(grepl("s1", diagnostic_df$name) == 1, "s1", 
                               ifelse(grepl("s2", diagnostic_df$name) == 1, "s2",
                                      ifelse(grepl("sep", diagnostic_df$name) == 1, "sep",
                                             ifelse(grepl("cont", diagnostic_df$name) == 1, "cont", 0))))

diagnostic_df$stream <- ifelse(grepl("C3_LS", diagnostic_df$name) == 1, "C3+LS",
                                             ifelse(grepl("LS", diagnostic_df$name) == 1, "LS",
                                                    ifelse(grepl("C3", diagnostic_df$name) == 1, "C3", 0)))

diagnostic_df$data <- ifelse(grepl("raw_diff", diagnostic_df$name) == 1, "raw diff",
                             ifelse(grepl("raw_avg", diagnostic_df$name) == 1, "raw avg",
                                    ifelse(grepl("growth_diff", diagnostic_df$name) == 1, "growth diff",
                                           ifelse(grepl("growth_avg", diagnostic_df$name) == 1, "growth avg", 
                                                  ifelse(grepl("raw_growth", diagnostic_df$name) == 1, "raw+growth",
                                                         ifelse(grepl("growth", diagnostic_df$name) == 1, "growth",
                                                                ifelse(grepl("raw", diagnostic_df$name) == 1, "raw",0)))))))
```

```{r}
# write table
write.csv(diagnostic_df, "diagnostics_pca_C3_raw.csv")
```
