---
title: "Plots for Season 1 Clusters on Raw Data"
output:
  html_document: default
  html_notebook: default
---

```{r}
##################################################################################
# inputs: CENT_showlevel.csv, s1_shows_best_clusters.csv
#
# purpose: Exploratory plots for raw and growth trends,
#          non-normalized impressions, clusters from normalized data
##################################################################################
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE, error = FALSE)
```

```{r}
library(dplyr)
library(ggplot2)
library(plotly)
library(scales)
```

```{r}
df <- read.csv("CENT_showlevel.csv") %>% select(-X) %>% 
  filter(Episode_num < 15 & Season_num > 0 & Season_num < 3)
lookup <- read.csv("s1_shows_best_clusters.csv")
df$clusters_C3_raw <- lookup$C3_raw_5kmeans[match(df$Show_Name, lookup$Show_Name)]
df$clusters_C3_growth <- lookup$C3_growth_5kmeans[match(df$Show_Name, lookup$Show_Name)]
df$clusters_LS_raw <- lookup$LS_raw_3dtw[match(df$Show_Name, lookup$Show_Name)]
df$clusters_LS_growth<- lookup$LS_growth_5tadpole[match(df$Show_Name, lookup$Show_Name)]
```

```{r}
my_theme <-  theme(panel.background = element_blank(), 
                   panel.grid.major = element_line(color = "#d8d8d8", linetype = "dotted"), 
                   panel.grid.major.x = element_blank(), 
                   plot.title = element_text(hjust = 0.5),
                   axis.title.y = element_blank(),
                   axis.line.y = element_blank(),
                   axis.ticks.y = element_blank(),
                   axis.line.x = element_line(color = "#d8d8d8", linetype = "dashed"),
                   strip.background = element_blank(), 
                   legend.position = "none")
```

# C3 Impressions

```{r, fig.height=8}
C3_raw <- ggplot(df %>% filter(is.na(clusters_C3_raw) == F)) +
  geom_line(aes(x = Episode_num, y = C3_Impressions, color = Show_Name), 
            se = F, method = "lm", alpha = 1, formula = y ~ 0 + x) +
  geom_smooth(aes(x = Episode_num, y = C3_Impressions), 
              color = "black", se = F, method = lm, linetype = "dashed") +
  facet_grid(clusters_C3_raw ~ Season_num) +
  my_theme + 
  labs(x = "Episode Number")

ggplotly(C3_raw) %>% 
  layout(title = "S1-S2 Trends (C3 Impressions by S1 Clusters)",
         autosize = FALSE, width = 650, height = 800, 
         margin = list(l = 100, 
                       r = 50, 
                       b = 100, 
                       t = 125))
```

```{r, fig.height=8}
C3_raw_linear <- ggplot(df %>% filter(is.na(clusters_C3_raw) == F)) +
  stat_smooth(aes(x = Episode_num, y = C3_Impressions, color = Show_Name), 
              geom = "line", se = F, method = "lm", alpha = 1) +
  stat_smooth(aes(x = Episode_num, y = C3_Impressions), 
              geom = "line", color = "black", se = F, method = "lm", 
              linetype = "dashed", alpha = 0.7) +
  facet_grid(clusters_C3_raw ~ Season_num) +
  my_theme +
  labs(x = "Episode Number")

ggplotly(C3_raw_linear) %>% 
  layout(title = "S1-S2 Linear Trends (C3 Impressions by S1 Clusters)",
         autosize = FALSE, width = 650, height = 800, 
         margin = list(l = 100, 
                       r = 50, 
                       b = 100, 
                       t = 125))
```

# LS Impressions

```{r, fig.height=8}
LS_raw <- ggplot(df %>% filter(is.na(clusters_LS_raw) == F)) +
  geom_line(aes(x = Episode_num, y = LS_Impressions, color = Show_Name), 
            se = F, method = "lm", alpha = 1, formula = y ~ 0 + x) +
  geom_smooth(aes(x = Episode_num, y = LS_Impressions), 
              color = "black", se = F, method = lm, linetype = "dashed") +
  facet_grid(clusters_LS_raw ~ Season_num) +
  my_theme + 
  labs(x = "Episode Number")

ggplotly(LS_raw) %>% 
  layout(title = "S1-S2 Trends (LS Impressions by S1 Clusters)",
         autosize = FALSE, width = 650, height = 800, 
         margin = list(l = 100, 
                       r = 50, 
                       b = 100, 
                       t = 125))
```

```{r, fig.height=8}
LS_raw_linear <- ggplot(df %>% filter(is.na(clusters_LS_raw) == F)) +
  stat_smooth(aes(x = Episode_num, y = LS_Impressions, color = Show_Name), 
              geom = "line", se = F, method = "lm", alpha = 1) +
  stat_smooth(aes(x = Episode_num, y = LS_Impressions), 
              geom = "line", color = "black", se = F, method = "lm", 
              linetype = "dashed", alpha = 0.7) +
  facet_grid(clusters_LS_raw ~ Season_num) +
  my_theme +
  labs(x = "Episode Number")

ggplotly(LS_raw_linear) %>% 
  layout(title = "S1-S2 Linear Trends (LS Impressions by S1 Clusters)",
         autosize = FALSE, width = 650, height = 800, 
         margin = list(l = 100, 
                       r = 50, 
                       b = 100, 
                       t = 125))
```

# C3 Growth

```{r, fig.height=8}
C3_growth <- ggplot(df %>% filter(is.na(clusters_C3_growth) == F)) +
  geom_line(aes(x = Episode_num, y = C3_Growth, color = Show_Name), 
            se = F, alpha = 1) +
  stat_smooth(aes(x = Episode_num, y = C3_Growth), 
              geom = "line", color = "black", se = F, 
              method = "lm", linetype = "dashed", alpha = 1) +
  facet_grid(clusters_C3_growth ~ Season_num) +
  coord_cartesian(ylim = c(0, 2.5)) +
  my_theme +
  labs(x = "Episode Number")

ggplotly(C3_growth) %>% 
  layout(title = "S1-S2 Trends (C3 Growth by S1 Clusters)",
         autosize = FALSE, width = 650, height = 800, 
         margin = list(l = 100, 
                       r = 50, 
                       b = 100, 
                       t = 125))
```

```{r, fig.height=8}
C3_growth_linear <- ggplot(df %>% filter(is.na(clusters_C3_growth) == F)) +
  stat_smooth(aes(x = Episode_num, y = C3_Growth, color = Show_Name), 
              geom = "line", se = F, method = "lm", alpha = 1) +
  stat_smooth(aes(x = Episode_num, y = C3_Growth), 
              geom = "line", color = "black", se = F, 
              method = "lm", linetype = "dashed", alpha = 1) +
  facet_grid(clusters_C3_growth ~ Season_num) +
  coord_cartesian(ylim = c(0.5, 1.5)) +
  my_theme +
  labs(x = "Episode Number")

ggplotly(C3_growth) %>% 
  layout(title = "S1-S2 Linear Trends (C3 Growth by S1 Clusters)",
         autosize = FALSE, width = 650, height = 800, 
         margin = list(l = 100, 
                       r = 50, 
                       b = 100, 
                       t = 125))
```

# LS Growth

```{r, fig.height=8}
LS_growth <- ggplot(df %>% filter(is.na(clusters_LS_growth) == F)) +
  geom_line(aes(x = Episode_num, y = LS_Growth, color = Show_Name), 
            se = F, alpha = 1) +
  stat_smooth(aes(x = Episode_num, y = LS_Growth), 
              geom = "line", color = "black", se = F, 
              method = "lm", linetype = "dashed", alpha = 1) +
  facet_grid(clusters_LS_growth ~ Season_num) +
  coord_cartesian(ylim = c(0, 2.5)) +
  my_theme +
  labs(x = "Episode Number")

ggplotly(LS_growth) %>% 
  layout(title = "S1-S2 Trends (LS Growth by S1 Clusters)",
         autosize = FALSE, width = 650, height = 800, 
         margin = list(l = 100, 
                       r = 50, 
                       b = 100, 
                       t = 125))
```

```{r, fig.height=8}
LS_growth_linear <- ggplot(df %>% filter(is.na(clusters_LS_growth) == F)) +
  stat_smooth(aes(x = Episode_num, y = LS_Growth, color = Show_Name), 
              geom = "line", se = F, method = "lm", alpha = 1) +
  stat_smooth(aes(x = Episode_num, y = LS_Growth), 
              geom = "line", color = "black", se = F, 
              method = "lm", linetype = "dashed", alpha = 1) +
  facet_grid(clusters_LS_growth ~ Season_num) +
  coord_cartesian(ylim = c(0.5, 1.5)) +
  my_theme +
  labs(x = "Episode Number")

ggplotly(LS_growth) %>% 
  layout(title = "S1-S2 Linear Trends (LS Growth by S1 Clusters)",
         autosize = FALSE, width = 650, height = 800, 
         margin = list(l = 100, 
                       r = 50, 
                       b = 100, 
                       t = 125))
```
